### ISSUE TITLE
Still camera

### ISSUE THREAD

**Issue by smasoudn** [ai-tor/DeepGTAV#1]
After copying the binary files, the camera view is fixed and it's not possible to play the game. In other words, the view point is fixed (ocean or some random scene). 

Could you please take a look into that issue?

**Comment by ai-tor** [comment]
The mod is intended to be used to collect a dataset. So the camera is fixed
in the front-center of the vehicle and the IA starts driving by itself, it
is the normal behaviour. What do you plan to use the mod for?

Thanks for trying it out!

El dt., 22 nov. 2016 a les 16:46, smasoudn (<notifications@github.com>) va
escriure:

**Comment by smasoudn** [comment]
Thanks a lot for sharing the code! Great job! 
In the beginning the character is in the room and I have to leave the room and kill enemies to get into the car.

While the image is still I cannot see enemies and kill them to get into the car :D Am I missing something? 
Maybe I can get into the car (without using the code), save the game and then re-run the game (load from where I saved) with your code?

**Comment by ai-tor** [comment]
The plugin should automatically put your player into a car and start
driving with the camera in the front, so I think that maybe it is not
loading properly. Could you please attach the logs generated by the asi
loader and scripthook in your game root directory?

El dt., 22 nov. 2016 a les 17:05, smasoudn (<notifications@github.com>) va
escriure:

**Comment by smasoudn** [comment]
Thanks a lot for quick response! 
Here is the asi loader log

// GTA V ASI LOADER (build May  2 2015)
//     (C) Alexander Blade 2015
LIB: "C:\Windows\system32\dinput8.dll" => 000007FEFAAA0000
API: "DirectInput8Create" => 000007FEFAAA4820
API: "DllCanUnloadNow" => 000007FEFAAB20DC
API: "DllGetClassObject" => 000007FEFAAB2014
API: "DllRegisterServer" => 000007FEFAAC1050
API: "DllUnregisterServer" => 000007FEFAAC1064
LOADER: Loading *.asi plugins
ASI: Loading "D:\DeepDive\DeepGTAV.asi"
     "DeepGTAV.asi" => 000007FEF7A20000
LOADER: Finished loading *.asi plugins



and here is the ScriptHookkV log

// GTA V SCRIPT HOOK (build Oct  5 2016, v1.0.877.1)
//     (C) Alexander Blade 2015-2016
[11:16:00] INIT: Started
[11:16:00] INIT: Success, game version is VER_1_0_877_1_NOSTEAM
[11:16:00] INIT: Registering script 'DeepGTAV.asi' (0x000007FEF7A2A530)
[11:16:17] INIT: Pool 1 extended
[11:16:17] INIT: Pool 2 extended
[11:16:17] INIT: Pool 3 extended
[11:16:17] INIT: Pool 4 extended
[11:16:23] INIT: GtaThread collection size 187
[11:16:23] INIT: wnd proc 0x00000000FFFF0C55
[11:16:23] INIT: IDXGISwapChain 0x000007FEF4555AE0 (0x000007FEF457B2F8)
[11:16:23] INIT: IDXGISwapChain set
[11:16:23] INIT: DX init started
[11:16:23] INIT: DX feature level B000
[11:16:23] INIT: DX init succeeded
[11:17:01] CORE: Requesting thread creation
[11:17:01] CORE: Creating threads
[11:17:01] CORE: Started control thread, id 27 active 1
[11:17:01] CORE: Started thread 'DeepGTAV.asi' (0x000007FEF7A2A530), id 28 active 1
[11:17:01] CORE: Launching main() for 'DeepGTAV.asi' (0x000007FEF7A2A530), id 28
[11:18:56] UNINIT: Unregistering script 'DeepGTAV.asi'

**Comment by ai-tor** [comment]
Hi! 

Thanks for the logs, everything seems pretty normal. I am not at home right now, but when I get there I will send you my save files to see if that is the problem. In the meanwhile, could you please check that everything is fine with your config.ini? For example, that the folder where you store the dataset exists.

Copy it here so I can see if there is anything wrong also :)

**Comment by smasoudn** [comment]
Thanks again Aitor for your time! I really appreciate your help!

Here is the config.ini file:

    [environment] 
    mode=0
    imageWidth=227
    imageHeight=227
    captureFreq=10
    datasetDir=C:\Users\l00357552\Downloads\DeepGTAV-master\DeepGTAV-master\bin\Release\data\
    maxDuration=1
    
    [scenario]
    setSpeed=15.0
    drivingStyle=0
    car=0
    weatherChangeDelay=600
    initialWeather=0
    initialHour=-1
    initialMinute=-1
    initialPosX=-1
    initialPosY=-1

and just to see an example of what I get, I've attached couple of sample images that have been stored in *datasetDir*.


![382](https://cloud.githubusercontent.com/assets/16642324/20565153/5694a00e-b15e-11e6-9ef3-8c85f0aedd00.png)
![126](https://cloud.githubusercontent.com/assets/16642324/20565157/5e42b49e-b15e-11e6-9063-ff21e8cb74a0.png)

and this is couple of lines in the *dataset.txt* file

    5 0.000000 0.000000 0.000000 -1.114084 0.000000 0.000000 0
    6 0.000000 0.000000 0.000000 -1.114084 0.000000 0.000000 0

Just in case, here is my email:  smasoudn@gmail.com 

Thanks again for your time!

**Comment by ai-tor** [comment]
Haha! I think I know which is the issue, you are starting the game from the beginning, so after the plugin is loaded, the game automatically changes the camera, player, scenario, etc... to set the initial bank robbery cinematic.

I will upload to this thread a save file where it is 100% complete and with lot of money in your pocket! I will also upload the save file into to the repo so this issue is not repeated again :)

Thank you very much for your feedback! 👍

**Comment by ai-tor** [comment]
Hi again!

Can you please uncompress and copy the attached files to Documents/Rockstar Games/GTA V/Profiles/<profile>? :)

Tell me how it goes!

[save_data.zip](https://github.com/ai-tor/DeepGTAV/files/609549/save_data.zip)

**Comment by smasoudn** [comment]
You are wonderful Aitor! Thanks so much :)  After adding the 100% complete save file it worked. 

However,  when I start the game, most of the time the car doesn't move and I have to restart the game.  Do you have any idea why this happens?

**Comment by ai-tor** [comment]
Well, this is a known bug, when I randomize the initial position sometimes it gets into bad places, such as very close to the water, or places where there are no roads and the game's AI doesn't know what to do. For now, the only way to get around it is to restart the game as you said...

At some point I will probably create a bag of initial positions that I know they work and randomize only around that set.

I am glad it worked finally! :)

**Comment by monajalal** [comment]
@ai-tor @smasoudn  any idea why I don't get the script hook v log with your version of script hook v in the bin folder of repo? I used to get script hook v log with the one downloaded from gta5 mod website.
![scriptlog](https://cloud.githubusercontent.com/assets/1892917/22050934/b7a0da94-dd04-11e6-8acf-0c891410db85.PNG)
