### ISSUE TITLE
Pressing F4 doesn't bring the Script Hook V menu, how to mod?

### ISSUE THREAD

**Issue by monajalal** [ai-tor/DeepGTAV#10]
I want to teleport or mod or use other facilities in Script Hook V menu. I used to be able to do so when I had the script hook v dll downloaded from gta5mod website. However, now pressing F4 is ineffective. How can I do so? Like how can I get on a helicopter or go to airport, etc?

Thanks,
Mona

**Comment by ai-tor** [comment]
Hi Mona,

You should put nativetrainer.asi that comes with the ScriptHookV package into the GTAV installation dir.

Cheers.
