### ISSUE TITLE
Reverse movement

### ISSUE THREAD

**Issue by elevir** [ai-tor/DeepGTAV#103]
Hello!

It seems that only forward movement is available, but it makes troubles such as stucking in a wall. So, is there any way to move backward on a vehicle by sending tuple (throttle, brake, steering)?

Thanks.

**Comment by ghost** [comment]
Isnt the car moving backwards when you have throttle at 0 and brake higher than 0.3 ?

**Comment by elevir** [comment]
@KemalAcar07 it isnt. I tried to use tuple (throttle = 0, break = 1.0 (or 0.5), steering = 0.0). Nothing is happen. Maybe problem in version of dll which I use. I use version of [@angelapper](https://github.com/angelapper/DeepGTAV) with rewarder fix. But i'm not sure that the problem in this.

**Comment by elevir** [comment]
the broblem was in wrong field name in Json :)
