### ISSUE TITLE
How to downgrade GTAV

### ISSUE THREAD

**Issue by mjjdick** [ai-tor/DeepGTAV#104]
Hi, all. I have downloaded the GTAV game in steam, but how can I downgrade the version to  1.0.1180.2 ?
anyone can help me ? I will be so grateful!

**Comment by mjjdick** [comment]
OK, I have found the solve method! just follow the instruction https://steamcommunity.com/sharedfiles/filedetails/?id=950470817

**Comment by Shawnxm** [comment]
> 
> 
> OK, I have found the solve method! just follow the instruction https://steamcommunity.com/sharedfiles/filedetails/?id=950470817

The page shows ERROR. sad...
