### ISSUE TITLE
Is there any way to Debug?

### ISSUE THREAD

**Issue by mjjdick** [ai-tor/DeepGTAV#106]
Hi, all, when I change the configure params, I did not find it works. Is there any way for me to debug the code or show the params in the game?

**Comment by corypaik** [comment]
Hi, did you ever find a way to do any debugging? I noticed there is a log file but it seems nothing writes to it, don't know if you have any insight on that.

**Comment by mjjdick** [comment]
@corypaik nope,I  haven't found a better way to debug~
