### ISSUE TITLE
More details about Installation

### ISSUE THREAD

**Issue by CarbonGU** [ai-tor/DeepGTAV#13]
Hi, it's a really good project!

Before installing your DeepGTAV, I need to buy the GTAV game software, and add DeepGTAV in the installation dirs. Right?

Thanks

**Comment by lbin** [comment]
@ai-tor Should I buy a windows version?

**Comment by ai-tor** [comment]
@lbin Would be nice to do the same with PS4 and XboxOne, but that is not suported :)

So yes, you need the PC version of the game

**Comment by lbin** [comment]
@ai-tor thanks, I only have PS4. PC version is more cheap:)

**Comment by IanKirwan** [comment]
Hi @ai-tor 

Do you know how to downgrade to GTAV 1.0.1103.2? My version is 1.0.231.0.

Many thanks in advance.
