### ISSUE TITLE
Sometimes the captured frames happen to be all/some black

### ISSUE THREAD

**Issue by monajalal** [ai-tor/DeepGTAV#14]
This is an example of what I am getting (literally all the captured frames for which the car was driving in the night)
![11068](https://cloud.githubusercontent.com/assets/1892917/22125129/1ff6113c-de58-11e6-91f5-2dc7cd795435.png)
This is a short video of the driving scene
https://www.instagram.com/p/BPdcKgBDHHZ/
Any idea what is this?
[dataset.txt](https://github.com/ai-tor/DeepGTAV/files/717780/dataset.txt)
Here's the dataset for 11100 png images captured (all black 🗡 )

**Comment by ai-tor** [comment]
Wow! Surprising result! It only happens at night? Are you sure?

**Comment by monajalal** [comment]
well, yes, it only happened for the sequence of video I shared on Instagram. I restarted the game it started from day to night and the captures from the night were not black. I am not sure what had happened. right now it is working fine.

**Comment by ai-tor** [comment]
It seems your setup has lots of random crashes. If you have other .asi plugins installed I recommend you to remove them, they may be causing unexpected behaviours

**Comment by monajalal** [comment]
This is my entire log
```
// GTA V SCRIPT HOOK (build Dec 15 2016, v1.0.944.2)
//     (C) Alexander Blade 2015-2016
[14:37:13] INIT: Started
[14:37:13] INIT: Success, game version is VER_1_0_944_2_NOSTEAM
[14:37:13] INIT: Registering script 'DeepGTAV.asi' (0x00007FF9912705A0)
[14:37:18] INIT: Pool 1 extended
[14:37:18] INIT: Pool 2 extended
[14:37:18] INIT: Pool 3 extended
[14:37:18] INIT: Pool 4 extended
[14:37:24] INIT: GtaThread collection size 188
[14:37:24] INIT: wnd proc 0x00000000FFFF0869
[14:37:24] INIT: IDXGISwapChain 0x00007FF9A62DD058 (0x00007FF9A6283440)
[14:37:24] INIT: IDXGISwapChain set
[14:37:24] INIT: DX init started
[14:37:24] INIT: DX feature level B000
[14:37:24] INIT: DX init succeeded
[14:38:04] CORE: Requesting thread creation
[14:38:04] CORE: Creating threads
[14:38:06] CORE: Started control thread, id 29 active 1
[14:38:06] CORE: Started thread 'DeepGTAV.asi' (0x00007FF9912705A0), id 30 active 1
[14:38:06] CORE: Launching main() for 'DeepGTAV.asi' (0x00007FF9912705A0), id 30
[15:04:52] UNINIT: Unregistering script 'DeepGTAV.asi'

```

I didn't have another .asi in the GTAV folder besides DeepGTAV.asi also according to your VPilot code seems like I can have various directories pointed for dataset, right? For now I have 30k images in one folder and then the camera started showing back of the car.

**Comment by ai-tor** [comment]
Looks like the script is stopping after half an hour.  What is the max duration value in _config.ini_?

**Comment by monajalal** [comment]
so max duration was equal to 1 and then I set it to 2 and then ran the game again and eventually ended up with camera showing back of car so I stopped it. Here's the dataset.txt
[dataset.txt](https://github.com/ai-tor/DeepGTAV/files/720513/dataset.txt)
also here's my config.ini:
[common]
mode=0
imageWidth=320
imageHeight=160
car=0
weatherChangeDelay=1000
initialWeather=-1
initialHour=-1
initialMinute=-1
initialPosX=-1
initialPosY=-1
maxDuration=2

[supervised]
setSpeed=15.0
drivingStyle=0
captureFreq=10
datasetDir=D:\DeepGTAV_dataset2\

[reinforcement]
reward=2
desiredSpeed=15.0
desiredAgressivity=0.5
host=144.92.237.238
port=8000

**Comment by ai-tor** [comment]
Hi @monajalal ,

It is normal that the camera stops pointing forward once the maxDuration time has been reached, because the script stops itself.

Regarding the black images, it is really strange... When you are creating a new dataset, do you create it in a new directory or do you overwrite an existing dataset? The latter may cause trouble.

**Comment by DavideA** [comment]
I don't know if this helps, but in my case the software was logging black images due to fullscreen mode.
Typing ALT + Enter solved it for me.

**Comment by ai-tor** [comment]
Hi @DavideA,

Thanks for your help, in theory, if you use the provided saved games the screen should start automatically at 800x600 in windowed mode, but cool to know that it doesn't work in full screen mode :)

**Comment by monajalal** [comment]
Unfortunately the problem is still persistent. I changed the maxDuration to 10 which I believe means 10 hours and after ~40 min into driving, they started being captured as black. Any thought is greatly appreciated. 
![yl](https://cloud.githubusercontent.com/assets/1892917/22282733/e4c0ff64-e2a3-11e6-81f0-3122bb93cf51.PNG)
Here's my config.ini:
```
[common]
mode=0
imageWidth=320
imageHeight=160
car=0
weatherChangeDelay=600
initialWeather=-1
initialHour=-1
initialMinute=-1
initialPosX=-1
initialPosY=-1
maxDuration=10

[supervised]
setSpeed=15.0
drivingStyle=0
captureFreq=10
datasetDir=D:\frames\

[reinforcement]
reward=2
desiredSpeed=15.0
desiredAgressivity=0.5
host=169.254.38.186
port=8000
```

**Comment by tyluckyma** [comment]
try not to minimize the screen

**Comment by twmht** [comment]
@ai-tor 

It seems that the "black image" problem only happens in full-screen mode.

Do you know how to solve it?
