### ISSUE TITLE
Game Update and Broken Hook

### ISSUE THREAD

**Issue by smasoudn** [ai-tor/DeepGTAV#15]
I am wondering if you have faced this issue or not but every once in a while the game is updated automatically and that causes the hook break.

Just wondering what do you do with this issue? How one can prevent the game from being updated?

**p.s.** I recently noticed that all repositories related to GTA have been removed from Craig Quiter's repository and Open-Ai. Does anyone know why?

**Comment by ai-tor** [comment]
Hi @smasoudn

I usually try to run the game offline by disabling the Internet connection. Has there been an update recently? I can check and fix it in a few days. 

Regarding OpenAI I am afraid I am not allowed to say anything about it, but probably the repos will be back again in a few days
