### ISSUE TITLE
Target labelling / image segmentation

### ISSUE THREAD

**Issue by revilokeb** [ai-tor/DeepGTAV#16]
Many thanks Aitor for making this great piece of work publicly available! 

In your ToDos you mention "Implement target labelling (vehicles, peds animals and hopefully traffic signs and map directions)". Apart from the RL part I am also very interested in labelling for ground truth generation, employing bounding boxes and - to the extent possible - image segementation (e.g. https://arxiv.org/abs/1610.01983). 

I went through your code / some of the comments, and the following questions came up my mind:
1.  wrt. Targets/Targets.cpp Row 54 (GET_PED_TYPE(peds[i] != 28 //ANIMAL): where in the lib are the integer values specified, i.e. how can I interpret any returned int from GET_PED_TYPE / GET_ENTITY_TYPE?  I couldnt find this...
2. to obtain other objects on the screen beyond vehicles, persons and pickups it seems that lib/main.h Row 103 (worldGetAllObjects) could do the job in a similar vein as you have done in lib/Target.cpp getPedsInScreen/getVehiclesInScreen; then using GET_ENTITY_COORDS the location of the object might be obtainable, for bounding-box generation GET_ENTITY_HEIGHT might be useful. But: I cant see any function GET_ENTITY_WIDTH / GET_ENTITY_DEPTH or similar. Are you aware of any other way to obtain object bounding boxes? And could a way (although very inefficient) to obtain pixel level object classes be to ask IS_ENTITY_AT_COORD for every object and every coordinate? Are you aware of anything more promising?

**Comment by ai-tor** [comment]
Hi!

Thank you for using it! I will answer your questions one by one:

1. I haven't defined any ENUM yet to tell which integer corresponds to each type, however some of these types can be found in native db: http://www.dev-c.com/nativedb/func/info/ff059e1e4c01e63c
As you see is a matter of reverse engineering, in the Internet there may even be more complete lists

2. Wrong! :) You have this awesome method GAMEPLAY::GET_MODEL_DIMENSIONS that can be used with ENTITY::GET_ENTITY_MODEL and voilà 👍 Regarding pixel level segmentation, I have not studied this field too much so I don't have a clear answer. Your solution is of course possible, but as you say it is slow, I know other research is being done in this direction using tools like ReShade but eventually it looks like none of them succeed to achieve fully automated segementation.

This project was started as part of my master's thesis but it looks like it is going to expand beyond that, pixel segmentation is not in the scope of the project so for now I won't deal with it, however once I deliver the thesis it is probable I take a look at it to see if I find a solution.

BTW, really nice questions, I actually had to answer them myself in the past, so you are in the good track.

**Comment by revilokeb** [comment]
@ai-tor many thanks, very helpful!
