### ISSUE TITLE
Set the camera to look back of the car

### ISSUE THREAD

**Issue by twmht** [ai-tor/DeepGTAV#17]
Hi @ai-tor ,

In your code, the camera rotation is set to the vehicle rotation.

However, I tried to set the camera rotation as the negative vehicle rotation in order to look back.

something like this

```
Vector3 rotation = ENTITY::GET_ENTITY_ROTATION(vehicle, 1);
CAM::SET_CAM_ROT(camera, -rotation.x, -rotation.y, -rotation.z, 1);
```

But the view is weird and not look back.

Any suggestion?

**Comment by ai-tor** [comment]
Hi @twmht 

Take into account that you are shifting the vector in all dimensions, to lookback you only need to shift the y direction. So:

CAM::SET_CAM_ROT(camera, rotation.x, -rotation.y, rotation.z, 1);

Relatively to the car, x is lateral displacement, y longitudinal and z up/down.

Also, remember to do this change both in the Scenario constructor and step methods.

Hope it works! :)

**Comment by twmht** [comment]
@ai-tor 

I have tried to only change the y-direction, but still not worked.

![image](https://cloud.githubusercontent.com/assets/1567200/22641485/e4954322-ec91-11e6-9459-d15d14667b85.png)


Here is the camera position.

```
CAM::ATTACH_CAM_TO_ENTITY(camera, vehicle, 0, -20.5, 0.8, TRUE);
```

**Comment by ai-tor** [comment]
Hi!

Nice, you now have it in the back, you now need to set the rotation also to:

```Vector3 rotation = ENTITY::GET_ENTITY_ROTATION(vehicle, 1);
CAM::SET_CAM_ROT(camera, rotation.x, -rotation.y, rotation.z, 1);```

Both in the constructor and the step methods.

**Comment by ai-tor** [comment]
Hi @twmht 

My mistake, GET_ENTITY_ROTATION doesn't return a vector, x, y and z and actually angles (pitch, yaw and roll). You yaw and pitch can remain constant, but roll needs to be shifted 180 degrees, so doing the sign change is ok, but I actually don't kno which one of the parameters is, either x, y or z. You will have to try one by one.

**Comment by twmht** [comment]
@ai-tor 

I have tried to change z only (to pass -z).

initially it looks like this 
![image](https://cloud.githubusercontent.com/assets/1567200/22673797/45c16e2a-ed17-11e6-873c-3b3a6991de71.png)

however, when the car's rotation changes, the camera may not look back.

For example, the camera is expected to look only back of the car, but it looks at car here.
![image](https://cloud.githubusercontent.com/assets/1567200/22673834/7bc32f18-ed17-11e6-95d3-ab0908806e61.png)

**Comment by ai-tor** [comment]
Hi @twmht 

Remember to refresh the rotation also in the step method, otherwise if the car moves, the camera doesn't refresh its position and always points in the same direction.
