### ISSUE TITLE
Set the camera above the car

### ISSUE THREAD

**Issue by DavideA** [ai-tor/DeepGTAV#18]
Hi, 
thank you for your work.

I am currently trying to add a camera that looks to the car from above. I'm trying in a trial and error way but  I'm struggling even understanding how the coordinate system is oriented. Any hint?
I believe the method ATTACH_CAM_TO_ENTITY is right for me I just need to set an offset along the proper dimension. Am I right? 

I'm changing the code in the scenario constructor and step method. Is it the only place where cameras get manipulated?

**Comment by ai-tor** [comment]
Hi Davide,

Yes, that's right, if you attach it to a car for example, it will follow it from above, which is cool.
x is east-west, y is north-south, and z is up-down. So in your case you need to set a huge positive z.
Regarding the camera rotation it is not so clear, you will need to try different combinations yourself.

Yes, those are the only places where they are manipulated.

**Comment by DavideA** [comment]
Thank you for your help.
Playing a bit with rotations I managed to get a decent result. What I did is:

1.  Change the camera attachment in `Scenario` constructor:
`CAM::ATTACH_CAM_TO_ENTITY(camera, vehicle, 0, 0, 30, TRUE);`
2. Change the camera rotation in `Scenario::step()` method:
`CAM::SET_CAM_ROT(birdeye_camera, -90, 0, rotation.z, 1);`
This results in the following [gif](http://gph.is/2kFTEs5).
Anyway, I'm still trying to have the camera completely solidal with the car (i.e. the car should always be "vertical")

Now I'm facing a second issue: let's say I want to save both the normal frontal view and the new birdeye view at each step of the environment. 
I created two distinct cameras, as follows:

//Puts camera on vehicle
rotation = ENTITY::GET_ENTITY_ROTATION(vehicle, 1);
CAM::DESTROY_ALL_CAMS(TRUE);
frontal_camera = CAM::CREATE_CAM("FRONTAL_CAMERA", TRUE);
CAM::ATTACH_CAM_TO_ENTITY(frontal_camera, vehicle, 0, 0.5, 0.8, TRUE);
CAM::SET_CAM_FOV(frontal_camera, 60);
//CAM::SET_CAM_ACTIVE(frontal_camera, TRUE);
CAM::SET_CAM_ROT(frontal_camera, rotation.x, rotation.y, rotation.z, 1);
CAM::SET_CAM_INHERIT_ROLL_VEHICLE(frontal_camera, TRUE);
CAM::RENDER_SCRIPT_CAMS(TRUE, FALSE, 0, TRUE, TRUE);

//Puts camera in bird's eye mode (tentative)
birdeye_camera = CAM::CREATE_CAM("BIRDEYE_CAMERA", TRUE);
CAM::ATTACH_CAM_TO_ENTITY(birdeye_camera, vehicle, 0, 0, 30, TRUE);
CAM::SET_CAM_FOV(birdeye_camera, 60);
CAM::SET_CAM_ROT(birdeye_camera, rotation.x, rotation.y, rotation.z, 1);
CAM::SET_CAM_INHERIT_ROLL_VEHICLE(birdeye_camera, TRUE);
CAM::RENDER_SCRIPT_CAMS(TRUE, FALSE, 0, TRUE, TRUE);

And in the environment i toggle cameras using `SET_CAM_ACTIVE` function. Is this the proper way?
What I get is the default camera, from the back of the car. I believe that this is due to the name of the cameras, that are different from the default `DEFAULT_SCRIPTED_CAMERA`. How can I save both frames?

Thank you for any help

**Comment by twmht** [comment]
@DavideA 

Have you ever tried this?

**Comment by twmht** [comment]
@DavideA 

I tried your configuration

```
CAM::ATTACH_CAM_TO_ENTITY(camera, vehicle, 0, 0, 30, TRUE);
CAM::SET_CAM_ROT(camera, -90, 0, rotation.z, 1);
```

the result is weird.

![image](https://cloud.githubusercontent.com/assets/1567200/22676509/d7b7fb78-ed26-11e6-8998-5c07ed46c939.png)


it looks up the sky, not look at the car.

Did you change other settings?

**Comment by ai-tor** [comment]
Hi @DavideA ,

Frames are currently stored by performing screenshots of the current game screen, so I don't actually know if it is possible to capture two different cameras at the same time, not at least with the current method.

Maybe it is possible, to do an screenshot, change camera, do another screenshot, change camera and so on, but it would add a lot of overhead.

I've not played with cameras a lot, not even in real life, so helping you figuring out the correct ROT and POS values is something I can't do currently. You can take a look here for other methods: http://www.dev-c.com/nativedb/ or check the GTAV forums, there are lot of answered questions: http://gtaforums.com/topic/788343-script-hook-v/

Tell me how it goes! :)

**Comment by DavideA** [comment]
@twmht no other modifications at all. Are you sure to call `CAM::SET_CAM_ROT` inside the step function?

@ai-tor The double screenshot method you mentioned was exactly my idea. The overhead would not be a problem since i plan to use it only in automated driving scenarios. I'll keep trying!

**Comment by JasmineDeng** [comment]
As a follow-up: I found 
`CAM::SET_CAM_ROT(camera, -90, 0, ENTITY::GET_ENTITY_HEADING(vehicle), 1);`
worked best for an overhead camera, so the camera would follow the direction the camera drives in.
