### ISSUE TITLE
Obtaining all objects in a frame together with their bounding boxes

### ISSUE THREAD

**Issue by revilokeb** [ai-tor/DeepGTAV#19]
Hi Aitor, still on my way to obtaining bounding boxes for all objects in a given frame :-) **I have done the following:**
1. I have introduced 4 small new methods in `SLScenario`:
 a. `updateCurrentObjects()` - gets an array of objects by using `worldGetAllObjects `and then checks `IS_ENTITY_ON_SCREEN` (similar to your code in `Targets.cpp`); called at the beginning of `SLEnvironment::saveSample()`  
 b. `getEntityType(Entity i)` - wrapper for `ENTITY::GET_ENTITY_TYPE(Entity)` 
 c. `getEntityModel(Entity i)` - wrapper for `ENTITY::GET_ENTITY_MODEL(Entity)`
 d. `getModelDimensions(Hash modelHash, Vector3* minimum, Vector3* maximum)` - wrapper for `GAMEPLAY::GET_MODEL_DIMENSIONS(Hash, Vector3, Vector3)`
2. In `SLEnvironment::saveSample()` I am calling the above methods and then write the Entity type and Entity dimensions (min.x, min.y etc) for each Object obtained via 1a. to another file 

**Observations are as follows**:
1. Depending on the scenery / frame I am getting between ~30 and ~300 objects
2. The Entity type is always zero for all objects except for the third object where it is 1
3. Coordinates are the same (non-zero, finite, not completely unreasonable by themselves) for all objects

Obviously that result is not what I want / expected. **My questions:** 1. is it reasonable to try obtaining all objects in a given frame using `worldGetAllObjects` (or is there something more appropriate that you are aware of)? 2. Anything else suspicious that you might notice by eyeballing this?

Many thanks in advance and best, Oliver

**Comment by ai-tor** [comment]
Hi Oliver,

Good to know you are making progress :)

What you are doing makes sense, but it is difficult to know if those observations are normal or not based only in your explanation. Coulld you attach the code, or send it to me via mail? I might be able to identify why the entity type is always zero. 

Getting around 30 or 300 might be normal depending on how you implemented the filter. Take into account that worldGetAllObjects can return lot of stuff, traffic signs, lights, guns(?) and others.

Cheers!

**Comment by revilokeb** [comment]
Hi Aitor, thank you for your assessment and your offer to look at the code. I will fiddle a bit for some more time myself but might come back on this issue, I'll leave it open for the moment. Best!

**Comment by ai-tor** [comment]
Sure, no prob! I'll be here!

**Comment by revilokeb** [comment]
Short update, from above observations 1. seems correct, 2. and 3. was a bug. I am now able to mark objects / vehicles / peds on the screen in real time (or slowed down) and write all kinds of seemingly sensible coordinates to files. However there are plenty other challenges :-)

Here are some that I couldnt satisfactory solve so far, maybe someone else knows:
1. Up to now I cant only get those objects / vehicles / peds that are visible from the camera. I have tried `ENTITY:IS_ENTITY_ON_SCREEN` and `ENTITY:IS_ENTITY_VISIBLE`, but both still give (many) entities that are NOT visible from my camera point of view, so each frame is cluttered with objects that I cant see.
2. I dont precisely understand how coordinates work, for example for a vehicle `GRAPHICS::_WORLD3D_TO_SCREEN2D` after `ENTITY::GET_ENTITY_COORDS` yields a position close to the center of the car but sometimes it seems higher positioned sometimes lower (i.e. not always strictly centered).
3. For bounding box coordinates I am trying the suggestions of @ai-tor described in another issue, yielding Vecor3 mincoord and Vector3 maxcoord. mincoord seems to always be negative, whereas maxcoord seems positive, so probably those are given relative to the center of the entity. But deriving a precise bounding box is still elusive.

I will update if I find ways to deal with the above.

**Comment by ai-tor** [comment]
Hi @revilokeb, 

1. This is solved in targets.cpp, the key is to check if the objects are in your line of sight (I am sorry I am in mobile phone and can't point you precisely to the method)

2. Yes,  depending from where you see it, objects may seem little higher or lower, this is something related to the internal game's representation. Nevertheless in your dataset you should use the normal 3D coordinates and not the screen ones, which are only useful for visualisation. 

3. No clue for now on that, will probably have a better understanding by next week. 

Good job!

**Comment by revilokeb** [comment]
@ai-tor with respect to 1: got it! This is ENTITY::HAS_ENTITY_CLEAR_LOS_TO_ENTITY, I didnt get what LOS was standing for ;-) now it makes sense, thank you.

**Comment by ai-tor** [comment]
Glad to help Oliver!

**Comment by ai-tor** [comment]
Hi @revilokeb ,

This week I have been working on the bounding boxes thing, I came up with this code to get the Front Upper Right and Back Lower Left corners of the 3D cube surrounding vehicles (should apply to pedestrians also). It may be useful to you if you haven't still succeeded, I will probably merge it with the project next week

```
Vector3 FUR; //Front Upper Right
Vector3 BLL; //Back Lower Lelft
Vector3 dim; //Vehicle dimensions
Vector3 upVector, rightVector, forwardVector, position; //Vehicle position
Vector3 min;
Vector3 max;

GAMEPLAY::GET_MODEL_DIMENSIONS(model, &min, &max)
ENTITY::GET_ENTITY_MATRIX(vehicle[i], &rightVector, &forwardVector, &upVector, &position); //Blue or red pill

//Calculate size
dim.x = 0.5*(max.x - min.x); 
dim.y = 0.5*(max.y - min.y); 
dim.z = 0.5*(max.z - min.z); 

FUR.x = position.x + dim.x*rightVector.x + dim.y*forwardVector.x + dim.z*upVector.x;
FUR.y = position.y + dim.x*rightVector.y + dim.y*forwardVector.y + dim.z*upVector.y;
FUR.z = position.z + dim.x*rightVector.z + dim.y*forwardVector.z + dim.z*upVector.z;

BLL.x = position.x - dim.x*rightVector.x - dim.y*forwardVector.x - dim.z*upVector.x;
BLL.y = position.y - dim.x*rightVector.y - dim.y*forwardVector.y - dim.z*upVector.y;
BLL.z = position.z - dim.x*rightVector.z - dim.y*forwardVector.z - dim.z*upVector.z;
```

**Comment by revilokeb** [comment]
@ai-tor many thanks for making this available again! I had just re-started yesterday to work on BB however had not come up with `ENTITY::GET_ENTITY_MATRIX(vehicle[i], &rightVector, &forwardVector, &upVector, &position)`. My approach had been to rotate the box defined by `GAMEPLAY::GET_MODEL_DIMENSIONS(model, &min, &max)` towards the forward vector. But your code is simpler and therefore much nicer.

However what I am failing to understand in your code so far: `static void GET_ENTITY_MATRIX(Entity entity, Any* p1, Any* p2, Vector3* p3, Vector3* p4)` available in natives.h expects `Any*` as second and third argument and `Any `is defined as `DWORD `which is an `unsigned long` essentially.  How do you easily convert from `Vector3*` to `Any*`? And how have you found out that p1, p2, p3 and p4 have the meaning they seem to have? Trying it out? :-) I had seen this functionality, too, but had no clue what they really mean...

**Comment by ai-tor** [comment]
Hi!

I am sorry, I forgot to explain it. The ```natives.h``` file is not updated to the last version of what's in the native db: http://www.dev-c.com/nativedb/

As you can see there, ```GET_ENTITY_MATRIX``` takes all the orientation vectors as parameters. So I didn't find out, some other cool human did :)

You will need to modify the ```natives.h```file to set that method so it can take the ```Vector3``` parameters.

Cheers!

**Comment by revilokeb** [comment]
Ah I see, I better check http://www.dev-c.com/nativedb/ more often!

**Comment by revilokeb** [comment]
@ai-tor Have you tested your above code by projecting it to the 2D by `GRAPHICS::_WORLD3D_TO_SCREEN2D(BLL.x, BLL.y, BLL.z, &blp2d.x, &blp2d].y)` and same for FUR? I am getting pretty insensible rectangles as BBs ...

So far I seem to have run into at least two issues:
1. `ENTITY::GET_ENTITY_MATRIX(entity, &rightVector, &forwardVector, &upVector, &position)` when compared to the output of `ENTITY::GET_ENTITY_FORWARD_VECTOR` seems to have the order mixed up: I am getting identical forwardVector if I exchange arguments forwardVector <-> rightVector in the `ENTITY::GET_ENTITY_MATRIX` call
2. GAMEPLAY::GET_MODEL_DIMENSIONS(Hash modelHash, Vector3 minimum, Vector3 maximum) does not seem to generally give symmetrical dimensions, i.e. most times abs(minimum.x) != abs(maximum.x) etc., therefore dim.x = 0.5*(max.x - min.x) above might be a bit problematic (quite often I am seeing slightly shifted boxes, or boxes too small on one side); as a solution I am now rotating all 8 corners of the model cuboid

Have you observed this too, or am I making a fundamental mistake somewhere?

**Comment by ai-tor** [comment]
Hi Oliver! 

I am not in front of my computer right now, but today I have been working on this and yeah, code was wrong but quite close to the final solution, which I tested today and works like a charm. 

Tomorrow I will attach the fixed snippet as I am already in bed :)

**Comment by revilokeb** [comment]
Hi Aitor, ok good to hear that you have a nice solution. I have spent quite a bit of time on it with certain successes but no ultimate breakthrough yet :-) Best!

**Comment by ai-tor** [comment]
Hi Oliver,

I am back, this is the code that has been used to prepare the brand new video: https://www.youtube.com/watch?v=StR9tuaIwYw

So guaranteed this works 100% :)

```
//Check if we see it (not occluded)
					GAMEPLAY::GET_MODEL_DIMENSIONS(model, &min, &max);
					ENTITY::GET_ENTITY_MATRIX(vehicles[i], &rightVector, &forwardVector, &upVector, &position); //Blue or red pill

					//Calculate size
					dim.x = 0.5*(max.x - min.x);
					dim.y = 0.5*(max.y - min.y);
					dim.z = 0.5*(max.z - min.z);

					FUR.x = position.x + dim.y*rightVector.x + dim.x*forwardVector.x + dim.z*upVector.x;
					FUR.y = position.y + dim.y*rightVector.y + dim.x*forwardVector.y + dim.z*upVector.y;
					//FUR.z = position.z + dim.y*rightVector.z + dim.x*forwardVector.z + dim.z*upVector.z;
					GAMEPLAY::GET_GROUND_Z_FOR_3D_COORD(FUR.x, FUR.y, 1000.0, &(FUR.z), 0);
					FUR.z += 2 * dim.z;


					BLL.x = position.x - dim.y*rightVector.x - dim.x*forwardVector.x - dim.z*upVector.x;
					BLL.y = position.y - dim.y*rightVector.y - dim.x*forwardVector.y - dim.z*upVector.y;
					//BLL.z = position.z - dim.y*rightVector.z - dim.x*forwardVector.z - dim.z*upVector.z;
					GAMEPLAY::GET_GROUND_Z_FOR_3D_COORD(BLL.x, BLL.y, 1000.0, &(BLL.z), 0);

					//DEBUG
					Vector3 edge1 = BLL;
					Vector3 edge2;
					Vector3 edge3;
					Vector3 edge4;
					Vector3 edge5 = FUR;
					Vector3 edge6;
					Vector3 edge7;
					Vector3 edge8;

					edge2.x = edge1.x + 2 * dim.y*rightVector.x;
					edge2.y = edge1.y + 2 * dim.y*rightVector.y;
					edge2.z = edge1.z + 2 * dim.y*rightVector.z;

					edge3.x = edge2.x + 2 * dim.z*upVector.x;
					edge3.y = edge2.y + 2 * dim.z*upVector.y;
					edge3.z = edge2.z + 2 * dim.z*upVector.z;

					edge4.x = edge1.x + 2 * dim.z*upVector.x;
					edge4.y = edge1.y + 2 * dim.z*upVector.y;
					edge4.z = edge1.z + 2 * dim.z*upVector.z;

					edge6.x = edge5.x - 2 * dim.y*rightVector.x;
					edge6.y = edge5.y - 2 * dim.y*rightVector.y;
					edge6.z = edge5.z - 2 * dim.y*rightVector.z;

					edge7.x = edge6.x - 2 * dim.z*upVector.x;
					edge7.y = edge6.y - 2 * dim.z*upVector.y;
					edge7.z = edge6.z - 2 * dim.z*upVector.z;

					edge8.x = edge5.x - 2 * dim.z*upVector.x;
					edge8.y = edge5.y - 2 * dim.z*upVector.y;
					edge8.z = edge5.z - 2 * dim.z*upVector.z;

					GRAPHICS::DRAW_LINE(edge1.x, edge1.y, edge1.z, edge2.x, edge2.y, edge2.z, 0, 255, 0, 200);
					GRAPHICS::DRAW_LINE(edge1.x, edge1.y, edge1.z, edge4.x, edge4.y, edge4.z, 0, 255, 0, 200);
					GRAPHICS::DRAW_LINE(edge2.x, edge2.y, edge2.z, edge3.x, edge3.y, edge3.z, 0, 255, 0, 200);
					GRAPHICS::DRAW_LINE(edge3.x, edge3.y, edge3.z, edge4.x, edge4.y, edge4.z, 0, 255, 0, 200);

					GRAPHICS::DRAW_LINE(edge5.x, edge5.y, edge5.z, edge6.x, edge6.y, edge6.z, 0, 255, 0, 200);
					GRAPHICS::DRAW_LINE(edge5.x, edge5.y, edge5.z, edge8.x, edge8.y, edge8.z, 0, 255, 0, 200);
					GRAPHICS::DRAW_LINE(edge6.x, edge6.y, edge6.z, edge7.x, edge7.y, edge7.z, 0, 255, 0, 200);
					GRAPHICS::DRAW_LINE(edge7.x, edge7.y, edge7.z, edge8.x, edge8.y, edge8.z, 0, 255, 0, 200);

					GRAPHICS::DRAW_LINE(edge1.x, edge1.y, edge1.z, edge7.x, edge7.y, edge7.z, 0, 255, 0, 200);
					GRAPHICS::DRAW_LINE(edge2.x, edge2.y, edge2.z, edge8.x, edge8.y, edge8.z, 0, 255, 0, 200);
					GRAPHICS::DRAW_LINE(edge3.x, edge3.y, edge3.z, edge5.x, edge5.y, edge5.z, 0, 255, 0, 200);
					GRAPHICS::DRAW_LINE(edge4.x, edge4.y, edge4.z, edge6.x, edge6.y, edge6.z, 0, 255, 0, 200);
```

**Comment by revilokeb** [comment]
Hi Aitor, whow really fantastic job the video!! All the more impressed as I have struggled myself to get it right. I will try it as soon as I am at a computer, and will close this issue directly when I am seeing the boxes myself on the screen ;-) Many thanks for making this available!!

**Comment by wujiyoung** [comment]
Hi  @Aitor,
I am trying to transform the 3D box to 2D box, I transform all 8 edges to screen coordinates with function `GRAPHICS::GET_SCREEN_COORD_FROM_WORLD_COORD`, and select Point(`min_x, min_y`), Pint(`max_x, max_y`) as left-top and right-bottom of the 2D bounding box. However, the transformed 2D bounding box is not correct. Following is a sample of the 2d bounding boxes. I am hoping for some advice from you !!
![result](https://user-images.githubusercontent.com/7520466/42164155-b20f8e7e-7e37-11e8-9b61-069d9079c73d.png)

**Comment by mjjdick** [comment]
@revilokeb @aitorzip Hi, I use the latest code to display boundingbox, and I found it still can not bounding the vehicle sometimes. Is there something wrong I did? Thx very much for you help！
