### ISSUE TITLE
Steering angle values are not between [-1 1]

### ISSUE THREAD

**Issue by smasoudn** [ai-tor/DeepGTAV#2]
Hi Aitor. Thanks again for your amazing code!
I found that sometimes the steering angle is more than 1 or less than -1. 
It seems that these values haven't been normalized, right?

Also, are these values in Radian [-pi pi]?

**Comment by ai-tor** [comment]
Hi again! :)

Those should be normalized, can you attach an example of your dataset file? 

Thanks!

Aitor.

**Comment by smasoudn** [comment]
Here's the part of the data set txt file:

    1 5.020366 0.000000 0.000000 1.114084 0.195328 -69.482224 0
    2 5.298885 0.166612 0.000000 1.114084 0.129882 -77.189590 -1
    3 5.984717 2.813320 0.000000 1.114084 0.164260 -78.917778 -1
    4 6.117838 5.195701 0.000000 1.114084 0.307285 -80.981628 -1
    5 6.497905 0.899466 0.000000 1.114084 0.406299 -82.855583 -1
    6 7.025465 3.654489 0.000000 1.114084 0.375907 -86.193314 -1
    7 7.499603 4.976974 0.000000 1.114084 0.483408 -84.289589 -1
    8 8.079679 4.694443 0.000000 1.114084 0.296821 -80.865349 -1
    9 9.077087 5.524535 0.000000 1.114084 0.400000 -118.368927 -1
    10 9.550818 7.073815 0.000000 0.969981 0.260528 -119.545113 -1
    11 10.150131 4.690406 0.000000 0.647385 0.332948 -84.867409 -1
    12 9.866303 5.875615 0.000000 0.325580 0.377800 -60.416786 -1
    13 9.323329 -2.838278 0.000000 -0.134738 0.400000 6.732968 -1
    14 8.978037 -3.770656 0.000000 -0.322392 0.400000 37.981647 1
    15 9.498058 -1.798396 0.000000 -0.136810 0.400000 19.142302 1
    16 9.830939 3.443851 0.000000 -0.079183 0.374610 7.039302 1
    17 10.058767 3.231854 0.000000 -0.049724 0.302284 2.944155 1
    18 10.338455 2.190654 0.000000 0.033778 0.400000 -0.943975 1
    19 10.587579 1.616693 0.000000 0.021196 0.400000 -4.916098 -1
    20 10.903221 1.946278 0.000000 -0.024700 0.400000 -1.941336 -1
    21 11.297790 2.238598 0.000000 -0.031698 0.400000 -0.303779 -1
    22 11.629865 2.759220 0.000000 0.024589 0.400000 -1.520929 -1
    23 12.004825 2.290173 0.000000 0.290565 0.290883 -24.285940 -1
    24 12.242899 2.999680 0.000000 0.172348 0.238101 -28.275553 -1
    25 12.507421 1.790032 0.000000 0.132418 0.367120 -13.505593 -1
    26 12.830221 2.116173 0.000000 0.328790 0.400000 -19.004604 -1
    27 13.190403 2.408960 0.000000 0.446324 0.400000 -30.657522 -1
    28 13.529008 2.881454 0.000000 0.353076 0.400000 -36.172009 -1
    29 13.775756 2.645351 0.000000 0.250742 0.400000 -24.904913 -1
    30 14.219947 1.927718 0.000000 0.203934 0.400000 -15.238915 -1

**Comment by smasoudn** [comment]
Is it because the steering turning angle is more than 360 degree (double turning the steering wheel)?
Also, 1 is equal to 180?

**Comment by ai-tor** [comment]
Hi!

There is no known method to actually get the steering wheel angle. So what
I actually do is to get the wheel angle, it is in radians I believe, but of
course it will never be greater than 180 deg, then I normalize dividing it
by the max.

The max angle was obtained experiment tally so it may be possible I just
didn't get the number right and it is greater than I initially thought.

I will fix this in the next release (2 days or so), for now you can just
divide the steering angle by 1.14 for your application :)

Thanks for your feedback! Much appreciate.
