### ISSUE TITLE
30 fps captureFreq ?

### ISSUE THREAD

**Issue by cory8249** [ai-tor/DeepGTAV#20]
Hi ai-tor,

Thank you for sharing this awesome project. I want to get 720P 30 fps videos, so I set captureFreq = 30 fps. But the output frames are only 15~20 fps and the game is not fluent. My PC is i7-7700K, 32G DDR4, GTX1070, 750G SSD. Is there any way to solve this problem? I've try to use lower profile in game setting, however it seems not work.

**Comment by ai-tor** [comment]
Hi @cory8249.

Usually in Deep Learning is not a good idea to have many temporary close samples in training as there is a lot of redundancy and can lead to overfitting more easily. The FPS should not be greater than 10 fps in most cases.

In your case at 30 fps the script is not able to capture the screen, resize it and store it in memory as PNG at such a rate :(

One thing that could help is to store the images in RAM and write them in physical memory in batches, for example every 10 images (depending on your RAM size). Still however, you would have a delay every time you store those images in the SSD.

**Comment by cory8249** [comment]
Actually I want to use it for object tracking, so 30 fps or even 60 fps is desirable for me. I've tried to use RAMDisk to store images, but it does not improve a lot. Anyway, many thanks for your quick rely. And I really hope that DeepGTAV can generate object bonding boxes (ground truth) soon. It would be amazing. Thank you again.

**Comment by ai-tor** [comment]
Hi @cory8249,

I am working on it, and also in a different way of storing the images, so maybe it will be able to work at 30 fps, but can't guarantee for now...

Thanks!
