### ISSUE TITLE
Vehicle dropped on random location and doesn't move

### ISSUE THREAD

**Issue by davidsandberg** [ai-tor/DeepGTAV#21]
Hi @ai-tor!
Thanks for a nice work!!
However, I run into some problem when running in dataset generation mode (mode=0). The plugin runs ok and generates images and a dataset.txt file in the specified dataset directory. But the vehicle gets dropped on some random spot in the world and then doesn't move. 
The problem looks related to #9 but I have added the contents of `SaveGame` to my profile and can load the saved game from the game menu:
![loadgame](https://cloud.githubusercontent.com/assets/15169058/22749180/b5c4f3c0-ee2c-11e6-92d4-f383841aec90.jpg)
Here are a couple of images from the dataset directory (different runs):
![15](https://cloud.githubusercontent.com/assets/15169058/22748145/6d299c9a-ee29-11e6-895c-93884f5b77ca.png)
![39](https://cloud.githubusercontent.com/assets/15169058/22748146/6d2b50d0-ee29-11e6-8843-03b50f1824f6.png)
The dataset description file (dataset.txt) doesn't look interesting either:
```
1 0.000000 -0.000000 0.000000 -1.000000 0.000000 0.000000 1
2 0.000000 0.000000 0.000000 -1.000000 0.000000 0.000000 0
3 0.000000 0.000000 0.000000 -1.000000 0.000000 0.000000 0
4 0.000000 0.000000 0.000000 -1.000000 0.000000 0.000000 0
```
My config.ini file looks like this:
```
[common]
mode=0
imageWidth=320
imageHeight=160
car=0
weatherChangeDelay=600
initialWeather=-1
initialHour=-1
initialMinute=-1
initialPosX=-1
initialPosY=-1
maxDuration=1

[supervised]
setSpeed=15.0
drivingStyle=0
captureFreq=10
datasetDir=c:\temp\GTAVDataset\

[reinforcement]
reward=2
desiredSpeed=15.0
desiredAgressivity=0.5
host=169.254.38.186
port=8000
```
Do you have any pointers for where I should look next?
I'm running the Steam edition of the game. Do you thing that could be related to the issue?
Thanks!!

**Comment by ai-tor** [comment]
Hi @davidsandberg ,

Thank you! Another user run into a similar problem, it looks it only happens with the Steam version of the game. And he solved the issue by not copying the cfg.dat and pc_settings.bin files and use the ones generated by the game (you can probably generate those again by the game without ScriptHook).

Tell me if that works

**Comment by davidsandberg** [comment]
Hi,
Sorry for the delay. I tried to let the game regenerate the files and replacing the ones in the game directory. Tried some different combinations but I didn't manage to get it to work. I think next step will be to try to get hold of the non-steam version of the game.
Thanks alot!

**Comment by monajalal** [comment]
For me, after I started the game in DeepGTAV2, even though I did the same procedure as in DeepGTAV1, the game can't load from yours. Indeed, nothing is in the load menu (it also created a new folder 32E6C4B4):
```
mona@DESKTOP-37GGNHL:/mnt/c/Users/mona/Documents/Rockstar Games/GTA V/Profiles$ tree
.
├── 32D6C4B4
│   ├── cfg.dat
│   ├── pc_settings.bin
│   ├── SGTA50015
│   └── SGTA50015.bak
└── 32E6C4B4
    ├── cfg.dat
    ├── cloudsavedata.dat
    └── pc_settings.bin


```

![20170403_132232](https://cloud.githubusercontent.com/assets/1892917/24624383/5316b226-1871-11e7-9c4f-cd861d64d6b4.jpg)


I tried removing everything again from profile and save it under the SavedGames as you provided but still the same problem. I didn't have this problem in DeepGTAV1. Can you please suggest a solution?
```
mona@DESKTOP-37GGNHL:/mnt/c/Users/mona/Documents/Rockstar Games/GTA V/Profiles$ tree
.
├── 32E6C4B4
│   ├── cfg.dat
│   ├── cloudsavedata.dat
│   └── pc_settings.bin
└── SaveGame
    ├── cfg.dat
    ├── pc_settings.bin
    ├── SGTA50015
    └── SGTA50015.bak

2 directories, 7 files
```

**Comment by monajalal** [comment]
I used this saved game from DeepGTAV1 and put it in 
`C:\Users\mona\Documents\Rockstar Games\GTA V\Profiles
`and now it is working. As said by Aitor previously, the game starts in random places so it is natural. For me the car had trottle automatically without me pressing any key but it wasn't intelligent so I am going to assume it is not using game AI. In DeepGTAV1 it was using game AI (if you set it in config.ini) and also started random places. 

https://drive.google.com/file/d/0B7j2NoupYo5gdTZDUVF6aFA5Mkk/view?usp=sharing
