### ISSUE TITLE
trouble with GAMEPLAY::SET_RANDOM_SEED

### ISSUE THREAD

**Issue by ndrplz** [ai-tor/DeepGTAV#22]
Hi @ai-tor, first thanks for your effort in this amazing project.

I was wandering if someone else has had trouble with the native `GAMEPLAY::SET_RANDOM_SEED(int time)`

I'm trying to be able to reproduce the same gameplay sequence more than once, but I had no luck up to now. It totally looks like `GAMEPLAY::SET_RANDOM_SEED(int)` does nothing at all: another possibillity is that other stuff that I'm not aware of silently overwrite the game engine random seed.

For instance, if I set at the beginning of `script.cpp`:

> 	float random_seed = 13.0;
	srand(random_seed);
	GAMEPLAY::SET_RANDOM_SEED(random_seed);

Now, every time that I restart the hook (by CTRL+R) I respawn at the same location, with the same weather (these stuff are controlled by srand) BUT nearby vehicles are different, the color of my car is different, peds are different etc.

Anyone maybe experienced the same problem?

Thank you,
Andrea

**Comment by ai-tor** [comment]
Hi @ndrplz,

Thanks for the compliments! 

It looks like there is no direct way of controlling how the game loads the entities. Probably your best option is to remove all the entities and manually setting them up specifying their models, position, behaviour (IA) etc... It is tedious, but if you write a nice method to do so you can generate any scene you want, which would be a nice feature, for the development of ADAS applications for example.

Cheers!

**Comment by ndrplz** [comment]
Thank you @ai-tor  for your response, 

Well this is really what I call bad news! :-) I was indeed trying to avoid the option you mentioned. 

I'll keep doing some research, I'll update this issue in case I discover something useful...

**Comment by ai-tor** [comment]
Ti auguro buona fortuna!
