### ISSUE TITLE
some nodeIds could not be found in paths.xml

### ISSUE THREAD

**Issue by twmht** [ai-tor/DeepGTAV#24]
Hi @ai-tor 

I have found that some nodeId could not be found in the `paths.xml`.

![image](https://cloud.githubusercontent.com/assets/1567200/23247337/7264f7e8-f9d4-11e6-9c76-d70f6d28f1e2.png)

Do you have any idea?

**Comment by ai-tor** [comment]
Hi @twmht ,

Is this happening only in some region or in most of the map? GTAV has been updated several times while paths.xml not, so maybe the file is outdated.

**Comment by twmht** [comment]
yup!

only happens  in some region (the location is shown in the figure),  I am not sure if this is due to the game update.

**Comment by ai-tor** [comment]
Will check that Bermuda Triangle

**Comment by twmht** [comment]
@ai-tor 

what is "Bermuda Triangle"

**Comment by ai-tor** [comment]
https://en.wikipedia.org/wiki/Bermuda_Triangle

**Comment by twmht** [comment]
Is it related to GTAV?

**Comment by ai-tor** [comment]
No, it is a "real" place, near Florida
