### ISSUE TITLE
line Point may not be located at the line

### ISSUE THREAD

**Issue by twmht** [ai-tor/DeepGTAV#25]
@ai-tor 

in some regions, the line points may not be located at the line

![image](https://cloud.githubusercontent.com/assets/1567200/23251617/f1716b16-f9e8-11e6-974b-5b916867f6da.png)

in the above figure, the line point is represented as light on the ground, but it is not located at lane line.

Any idea?

**Comment by ai-tor** [comment]
Hi @twmht ,

There is a piece of code in LaneRewarder.cpp, setLinePoints that looks like this:

```
if (link.attr.width > 0) { //Usually urban scenarios
		lineOffset = laneWidth / 2;
		starti = 0;
	}
	else if (link.attr.lanesOut == 0){ //Usually interurban scenarios TODO

		if ((link.attr.lanesIn % 2) == 0) {
			lineOffset = 0;
			linesIn = (linesIn / 2) + 1;
			starti = -(linesIn - 1);
		}
		else {
			lineOffset = laneWidth / 2;
			linesIn = linesIn / 2;
			starti = -linesIn;
		}

		linesOut = starti; //Skips linesOut loop
	}
	else { //Urban and interurban scenarios
		lineOffset = 0;
		starti = 1;

		linePoint.coord = node->coord;
		linePoint.laneIn = false;
		link.linePoints.push_back(linePoint);
}
```
In this piece of code I set a line offset and a starting point to start looking for lines to the left and to the right of the node. The main problem with lanes is to know:

1. How many lanes there are given a node
2. Where is the node located (in the middle of a lane, or in a line)

This two points appear to be related to 3 properties found in paths.xml for a given node. Width (a value between 0 and 5 I believe), lanesIn and lanesOut (which appear to indicate the number of lanes in one direction and number of lanes in another direction, but I believe it is not always that case).

So the key thing here is to translate those attributes to number of lanes and line offset, which is what I am trying to do in this code snippet.

As you see, for this road, it is not working, meaning that probably my algorithm does not generalize for the full map.

We should check what conditions are being entered here and see why it is not working for this road, and then see if we can come up with something better, that hopefully will work everywhere. :)

**Comment by twmht** [comment]
@ai-tor 

yup! I also found that some two-lane road have unequal widths on each of its lanes. So if the given width is fixed, the line point of the other lane may not be located well.

**Comment by twmht** [comment]
@ai-tor 

I found that in your code, you specify the default density and speed for each node, do you know the meaning of these two attributes?

**Comment by ai-tor** [comment]
Hi @twmht 

Sounds like speed indicates the mean traffic velocity and density the mean traffic density for that node, but not completely sure. Also the values don't have clear units, they are more like "levels"

**Comment by twmht** [comment]
@ai-tor 

thanks!

just curious, why you set the default value for speed=4 and density=-1 for each node?

```
for (object; object; object = object->NextSiblingElement()) {
		if (object->Attribute("class", "vehiclenode")) {
			tNode node = { 0 };
			node.attr.speed = 4;
			node.attr.density = -1;
```

I think it will be ok if the nodes have no default value for these two attributes?

**Comment by chizhang529** [comment]
Hi @twmht 

Would you please tell me which native commands you used to draw text on the screen and put lights on the ground?
