### ISSUE TITLE
Support for airplanes? 

### ISSUE THREAD

**Issue by elsewhat** [ai-tor/DeepGTAV#27]
As a GTA Mod developer I got a request over linkedin from a research intern which wanted to use the DeepGTAV to train flying airplanes instead of just cars.

Would be very interesting to see what kind of learning is possible when you have a more complicated scenario.

Had a quick look at the code and this will require a few modifications. 
SLScenario.cpp 
Uses AI::TASK_VEHICLE_DRIVE_WANDER. This native API does not work for airplanes, instead something like AI::TASK_PLANE_MISSION(pedDriver, pedVehicle, 0, 0, waypointCoord.x, waypointCoord.y, waypointCoord.z + height_above_ground, 4, 30.0, 50.0, -1, vehicleMaxSpeed, 50); must be used.

SLScenario.cpp  also has methods for getVehicleSteeringAngle and similar. These are direct memory access reads which probably is slightly different for airplanes. 

RLScenario.cpp
Has the performActions method which uses the native API to control the vehicle. One example is CONTROLS::_SET_CONTROL_NORMAL(27, 59, steering); //[-1,1] 
For aircrafts there is probably another set of controls which needs to be done . The first parameter is the group which should be 25 for planes (INPUTGROUP_FLY) . Not sure exactly which controls should be used to control the plane, https://github.com/GTA-Network/GTAVTools/blob/master/GTAVHook/Input.h has a list of values that may be used

**Comment by ai-tor** [comment]
Hi @elsewhat,

Thanks for your info! DeepGTAV has been developed with self-driving cars in mind, but it would be awesome to see a fork that works with planes.

Good job!

**Comment by elsewhat** [comment]
Thanks for the quick response,

See that the output from the model also need to include pitch and roll values.

But perhaps the most difficult task is to come up with some good reward functions. 
The self-driving car gets constant rewards based on the LaneRewarder, but it's hard to find a similar one for flying. You can probably define an air-corridor but it's really difficult to follow and any error in the output quickly means the reward goes down to zero for a long time.

**Comment by ai-tor** [comment]
Hi @elsewhat ,

The reward will depend on the objective you want to accomplish. If you want to keep an stable flight, you could probably set a reward based on distance to ground and set speed.

If you want to perform cool acrobatics, you could probably reward fast changes of roll, pitch and so, and of course, set it negative when a collision occurs.
