### ISSUE TITLE
JSON data format (x,y,z,heading)

### ISSUE THREAD

**Issue by cory8249** [ai-tor/DeepGTAV#28]
Hi ai-tor,

Could you please explain the meaning of JSON data format ?

'heading': 205.79498291015625
'FUR': [-49.6263427734375, 64.6822509765625, 4.7122039794921875]
'BLL': [-50.583251953125, 73.230224609375, 1.2143640518188477]

I don't really understand the GTAV coordinate system, how can we map this value into 2D image position (like original bounding box (top, left) (bottom, right)) 

Thanks a lot!

**Comment by ai-tor** [comment]
Hi @cory8249 ,

Thanks for asking! I still need to add that info to the README file. The coordinates are given relative to the center of your vehicle.

FUR stands for Front Upper Right and BLL for Back Lower Left, so those are the Front Upper Right and Back Lower Left corners of the vehicle or ped relative to your vehicle.

Converting those world coordinates to 2D screen coordinates is not an easy task, but I will add code to provide the 2D coordinates also, hopefully on Monday.

Best,

Aitor.

**Comment by cory8249** [comment]
Hi @ai-tor ,

Thank you for a quick reply. I am now working on it. I think I can map it into a spherical coordinate system.

But now how to get current camera's direction?  (0~360 degree)
How can I use this function to return current camera's direction to JSON ?

void Scenario::setDirection(){
    int direction;
    float distance;
    Document::AllocatorType& allocator = d.GetAllocator();
    PATHFIND::GENERATE_DIRECTIONS_TO_COORD(dir.x, dir.y, dir.z, TRUE, &direction, &vehicle, &distance);
    Value _direction(kArrayType);
    _direction.PushBack(direction, allocator).PushBack(distance, allocator);
    d["direction"] = _direction;
}

Thanks a lot

**Comment by ai-tor** [comment]
Hey! 

This function returns directions to a given coordinate point, like the GPS devices do: "In 200 m turn right".

It doesn't give the direction of the camera or vehicle. Why do you need the camera's heading?

**Comment by cory8249** [comment]
Oh, I misunderstood this function.

I found that object's x, y, z is relative to player's vehicle absolute position, right?
So if we get camera's angle, we can project 3D objects into 2D plane

![image](https://cloud.githubusercontent.com/assets/7524724/23562416/4ba53442-007d-11e7-9bf4-6d54caad479b.png)

**Comment by ai-tor** [comment]
Hi!

The objects returned by DeepGTAV are all the ones that are inside the screen region, so I may be wrong but I think the camera heading is not necessary. What do you think?

**Comment by cory8249** [comment]
I use these API to get player's vehicle heading, pitch, roll.
	float heading = ENTITY::GET_ENTITY_HEADING(vehicle);
	float pitch = ENTITY::GET_ENTITY_PITCH(vehicle);
	float roll = ENTITY::GET_ENTITY_ROLL(vehicle);

And I think I figure out the GTAV coordinate system.

![image](https://cloud.githubusercontent.com/assets/7524724/23564994/e03ced6c-0086-11e7-9d70-423e101b6eef.png)

![image](https://cloud.githubusercontent.com/assets/7524724/23565384/5ca2ce48-0088-11e7-8d9f-46905302f40b.png)

**Comment by cory8249** [comment]
Yeah,

I found there is already build-in API to get 3D-2D projection, super easy!!

void Scenario::setVehiclesList(){
...
float screen_x, screen_y;
GRAPHICS::_WORLD3D_TO_SCREEN2D(position.x, position.y, position.z, &screen_x, &screen_y);
...
}

**Comment by revilokeb** [comment]
@cory8249 I thought the same but whereas 3D bounding boxes fit the vehicle / ped pretty well, running `_WORLD3D_TO_SCREEN2D` on the corners of the 3D bounding boxes does not seem to give good results in many cases (projected corner points do not match the corner points of the 3D bounding box very well) - see e.g. motorcyclist, but also the white car with red stripe:

![grafik](https://cloud.githubusercontent.com/assets/10588773/23633757/505609d4-02c7-11e7-82d9-1a91f542b2e5.png)

Or are your projections looking nicer?

**Comment by ai-tor** [comment]
@crizCraig, the beautiful mind behind Deepdrive came up with some useful code to reliably project 2D coordinates from 3D, because as @revilokeb says ```_WORLD3D_TO_SCREEN2D``` does not give good results:

```
static Point get_2d_from_3d(const int& cam_entity, const Eigen::Vector3d& vertex, const Eigen::Vector3d& cam_coords, const Eigen::Vector3d& cam_rotation, const double& cam_near_clip, const double& cam_field_of_view, const bool& draw_debug = false)

{

	// Inspired by Artur Filopowicz: Video Games for Autonomous Driving: https://github.com/arturf1/GTA5-Scripts/blob/master/Annotator.cs#L379

	static const Eigen::Vector3d WORLD_NORTH(0.0, 1.0, 0.0);

	static const Eigen::Vector3d WORLD_UP(0.0, 0.0, 1.0);

	static const Eigen::Vector3d WORLD_EAST(1.0, 0.0, 0.0);;



	auto theta = (M_PI / 180.0) * cam_rotation;



	// camera direction, at 0 rotation the camera looks down the postive Y axis 

	auto cam_dir = Utils::rotate(WORLD_NORTH, theta);

	if (draw_debug)

	{

		auto cam_dir_line_end = cam_dir + cam_coords;

		GRAPHICS::DRAW_LINE(cam_coords.x(), cam_coords.y(), cam_coords.z(), cam_dir_line_end.x(), cam_dir_line_end.y(), cam_dir_line_end.z(), 0, 255, 0, 200);

	}



	auto clip_plane_center = cam_coords + cam_near_clip * cam_dir;

	auto camera_center = -cam_near_clip * cam_dir;



	auto near_clip_height = 2 * cam_near_clip * tan(cam_field_of_view / 2. * (M_PI / 180.)); // field of view is returned vertically

	BOOST_LOG_TRIVIAL(info) << "near_clip_height " << near_clip_height;



	auto near_clip_width = near_clip_height * GRAPHICS::_GET_SCREEN_ASPECT_RATIO(false);



	const Eigen::Vector3d cam_up = rotate(WORLD_UP, theta);

	const Eigen::Vector3d cam_east = rotate(WORLD_EAST, theta);

	const Eigen::Vector3d near_clip_to_target = vertex - clip_plane_center;

	Eigen::Vector3d camera_to_target = near_clip_to_target - camera_center; // Total distance - subtracting a negative to add clip distance

	if (draw_debug)

	{

		auto cam_up_end_line = cam_up + cam_coords;

		GRAPHICS::DRAW_LINE(cam_coords.x(), cam_coords.y(), cam_coords.z(), cam_up_end_line.x(), cam_up_end_line.y(), cam_up_end_line.z(), 100, 100, 255, 200);

		auto cam_east_end_line = cam_up + cam_coords;

		GRAPHICS::DRAW_LINE(cam_coords.x(), cam_coords.y(), cam_coords.z(), cam_east_end_line.x(), cam_east_end_line.y(), cam_east_end_line.z(), 100, 100, 255, 200);

		auto del_draw = cam_coords + near_clip_to_target;

		GRAPHICS::DRAW_LINE(clip_plane_center.x(), clip_plane_center.y(), clip_plane_center.z(), del_draw.x(), del_draw.y(), del_draw.z(), 255, 255, 100, 255);

		auto viewerDistDraw = cam_coords + camera_to_target;

		GRAPHICS::DRAW_LINE(cam_coords.x(), cam_coords.y(), cam_coords.z(), viewerDistDraw.x(), viewerDistDraw.y(), viewerDistDraw.z(), 255, 100, 100, 255);

	}



	Eigen::Vector3d camera_to_target_unit_vector = camera_to_target * (1. / camera_to_target.norm()); // Unit vector in direction of plane / line intersection



	// calc distance from camera to point on the view plane by scaling the near_clip distance by 1 / cos of the angle between camera->target (camera_to_target_unit_vector) and camera->near_clip_center (cam_dir)

	double view_plan_dist = cam_near_clip / cam_dir.dot(camera_to_target_unit_vector);



	Eigen::Vector3d up3d, forward3d, right3d;

	Utils::get_direction_vectors(cam_entity, up3d, forward3d, right3d);



	Eigen::Vector3d new_origin = clip_plane_center + (near_clip_height / 2.) * cam_up - (near_clip_width / 2.) * cam_east;

	if (draw_debug)

	{

		auto top_right = new_origin + near_clip_width * right3d;

		GRAPHICS::DRAW_LINE(new_origin.x(), new_origin.y(), new_origin.z(), top_right.x(), top_right.y(), top_right.z(), 100, 255, 100, 255);



		auto bottom_right = top_right - near_clip_height * up3d;

		GRAPHICS::DRAW_LINE(bottom_right.x(), bottom_right.y(), bottom_right.z(), top_right.x(), top_right.y(), top_right.z(), 100, 255, 100, 255);



		auto bottom_left = bottom_right - near_clip_width * right3d;

		GRAPHICS::DRAW_LINE(bottom_right.x(), bottom_right.y(), bottom_right.z(), bottom_left.x(), bottom_left.y(), bottom_left.z(), 100, 255, 100, 255);



		GRAPHICS::DRAW_LINE(bottom_left.x(), bottom_left.y(), bottom_left.z(), new_origin.x(), new_origin.y(), new_origin.z(), 100, 255, 100, 255);

	}



	Point ret;

	bool use_artur_method = false;

	if ( use_artur_method )

	{

		Eigen::Vector3d view_plane_point = view_plan_dist * camera_to_target_unit_vector + camera_center;

		view_plane_point = (view_plane_point + clip_plane_center) - new_origin;

		double viewPlaneX = view_plane_point.dot(cam_east) / cam_east.dot(cam_east);

		double viewPlaneZ = view_plane_point.dot(cam_up) / cam_up.dot(cam_up);

		double screenX = viewPlaneX / near_clip_width;

		double screenY = -viewPlaneZ / near_clip_height;

		ret = { screenX, screenY };

	}

	else

	{

		auto intersection = cam_coords + view_plan_dist * camera_to_target_unit_vector;

		if (draw_debug)

		{

			draw_marker(to_shared_mem_vector(intersection), 255, 0, 0, 0.025);

		}

		auto center_to_intersection = clip_plane_center - intersection;

		auto x_dist = center_to_intersection.dot(right3d);

		auto z_dist = center_to_intersection.dot(up3d);

		auto screen_x = 1. - (near_clip_width / 2. + x_dist) / near_clip_width;

		auto screen_y = (near_clip_height / 2. + z_dist) / near_clip_height;

		ret = { screen_x, screen_y };

	}
	return ret;
}
```
I will merge this into DeepGTAV but for now you can try it yourselves in your set-ups :)

**Comment by revilokeb** [comment]
@ai-tor very helpful again, thanks so much, also of course to @crizCraig! Do you also happen to have `Utils::get_direction_vector`s and `Utils::rotate` flying around? I guess however that it can be implemented more or less quickly using Eigen https://eigen.tuxfamily.org/dox/group__TutorialGeometry.html

**Comment by ai-tor** [comment]
Hi!

Don't have them, but that's basic algebra stuff, so that's a matter of "standing on the shoulder of giants" :)

**Comment by revilokeb** [comment]
You are right, in addition https://github.com/arturf1/GTA5-Scripts/blob/master/Annotator.cs#L458 can help too :-) (which seems a nice source of info by itself)

**Comment by lunzueta** [comment]
Hi @ai-tor. I have a couple of questions about the code you provided above  for the calculation of the 2D projections:
- What does the function Utils::get_direction_vectors() do, exactly? (I can't find where this comes from)
- Why are there two alternatives, based on the boolean value of "use_artur_method"? What's best and why?

Thanks for sharing this great work :)

**Comment by dtmoodie** [comment]
Hello,

Does anyone have a working implementation for projecting points onto the image?  I've gotten the above code mostly working but it isn't quite right.:

![download](https://cloud.githubusercontent.com/assets/7254941/25114527/3122b0c2-23cd-11e7-9fe6-9eeeea84643b.png)

**Comment by dtmoodie** [comment]
I've fixed the output, it seems mostly correct, however not as tight as I would like.  The implementation looks for the min / max in x and y based on the projection of the 8 3d corner points onto the image.

**Comment by ai-tor** [comment]
Would you like to submit a pull request? :)

**Comment by dtmoodie** [comment]
Sure just let me finish cleaning it up a bit.

**Comment by ai-tor** [comment]
Thanks :)
