### ISSUE TITLE
How to safely close tcp connect, without ctrl-c

### ISSUE THREAD

**Issue by fevemania** [ai-tor/DeepGTAV#29]
When connect from Ubuntu to Windows, I could success connect to GTA5 for the second times with one ctrl-c interrupt between two connection, but when the third time to connect, the connection is broken. I always have to restart the game to reconnect it. Is there any method for me to do multi-test on send message without reopen GTA games?

(But with Windows to Windows via localhost, it all fine)

**Comment by ai-tor** [comment]
Hi @fevemania,

Sorry for the delay. This is a known bug which I need to trace down to the root cause, will fix it in a few days.

**Comment by WenchaoDing** [comment]
Hi @ai-tor ,
Thanks for your efforts! It is an amazing tool.
I am wondering whether you have some idea about how to solve this issue. I am also bothered by this issue a lot.  Thanks!

**Comment by ai-tor** [comment]
Hi!

I made some changes and done some tests with the last version, it is working fine for me doing it through a Wifi connection. I can restart indefinitely from an Ubuntu machine.

Can you check if it is working for you?

**Comment by IanKirwan** [comment]
Hi @ai-tor,

The server still locks up for me on a single machine set-up after breaking the client twice. GTAV restart required. Still trying to understand the server side code to little hope of me debugging it yet.
