### ISSUE TITLE
script hook v error with GTA 1.0.1011.1

### ISSUE THREAD

**Issue by bn2302** [ai-tor/DeepGTAV#30]
Hi, 

since the resent GTA V update, DeepGTAV doesn't start. The error (SCRIPT HOOK V CRITICAL ERROR) mentions that the script hook version is incompatible with the game.

Best, 
Bastian

**Comment by ai-tor** [comment]
Hi, 

That's right. We need to wait until Scripthook is updated, which hopefully will be soon. Then I will push the update.

**Comment by ai-tor** [comment]
Solved

**Comment by bn2302** [comment]
Great, thanks a lot. 

PS: Great work, you've pulled of with DeepGTAV
