### ISSUE TITLE
Collecting depth data ? Positions of other vehicles surrounded ?

### ISSUE THREAD

**Issue by zuoxingdong** [ai-tor/DeepGTAV#31]
Firstly, thanks so much for this great repo. I have two short questions. 

1. Is it possible to receive RGB-D data ? So that some 'mapping' problems can be done. 

2. Is it possible to receive the positions of other vehicles surrounded ?

**Comment by ai-tor** [comment]
Hi! 

1. It is not possible at the moment, but it will be in the future, hopefully in a month. Not by me but by another contributor. 

2. It is possible! Just send the start message with vehicles set to true and DeepGTAV will answer you back with data from the surrounding vehicles, such as position, speed and heading.

**Comment by prshnthrv** [comment]
Is there any update on depth data collection?

**Comment by ai-tor** [comment]
Not yet as far as I know, will ask

**Comment by dtmoodie** [comment]
I too would like to know, otherwise I'd be interested in starting to implement depth collection.

**Comment by ai-tor** [comment]
In this project there is nothing being done, although I know one guy is doing its PHd around this, but I don't know if it will be freely shared.

Anyway, any contribution is welcome, and this would be super important. 

Seems that the way to go is by using a shader.

**Comment by dominikandreas** [comment]
Take a look at https://github.com/umautobots/GTAVisionExport from the paper "[Driving in the Matrix: Can Virtual Worlds Replace Human-Generated Annotations for Real World Tasks](https://arxiv.org/abs/1610.01983)". They already implemented a lot awesome stuff for data collection (including depth maps). Would be great if some of that could be integrated here

**Comment by ai-tor** [comment]
Wow! I'll take a look at that!

**Comment by prshnthrv** [comment]
Wow looks good. We have ended up doing something very similar.

**Comment by dominikandreas** [comment]
I spent quite a while trying to get the GTAVisionExport native plugin to work, but unfortunately the extracted depth and stencil buffers are never valid (either nonexistent or filled with zeros). 

@prshnthrv would it be possible for you to share your solution?

**Comment by vicky970125** [comment]
sorry to bother you,but i am not quite understand how to get the information about surrounding vehicles,could you please give more details about that?
