### ISSUE TITLE
Data Collection: Get stuck with trees, killed by police etc... within a few hours

### ISSUE THREAD

**Issue by zuoxingdong** [ai-tor/DeepGTAV#34]
I was running `dataset.py` to collect the dataset with default settings, for 100 hours. 

However, each time after just a few hours, the collection is disrupted by some accident in the game, either get stuck with trees, or surrounded by many car without moving, some time it even to be chased by police and being killed etc. 

Is it possible to make it more stable ?

**Comment by yanzheng000** [comment]
Hello, how to run dataset.py?
just set ip in code and use "python dataset.py" ?

**Comment by zuoxingdong** [comment]
@yanzheng000  Yes, exactly. Make sure that your Windows machine set up the same port that is defined in `dataset.py`

**Comment by yanzheng000** [comment]
Thank you very much. And do you know how to send JSON commend? In "drive.py". after "successfully connected to gta v" there is no where in terminal for me to enter commend..

**Comment by zuoxingdong** [comment]
@yanzheng000 The function `run()` takes the frame and the vector it returns are actually the command. You are define your model inside this function.

**Comment by zxzhijia** [comment]
I believe his code just let the car to run forward. Not autonomous driving by now.

**Comment by zxzhijia** [comment]
@zuoxingdong So are you using your own autonomous driving code in run() to collect data? Sorry, I'm a little confused by your question?

**Comment by cory8249** [comment]
@zuoxingdong This code would let the car drive autonomously (by defined paths.xml, not AI) as far as I tested last month

**Comment by ai-tor** [comment]
@zxzhijia `drive.py` in VPilot will just run the vehicle forward as an example. As @zuoxingdong says, you will need to create your own autonomous driving agent and put it in the code if you want it to do something "useful"
