### ISSUE TITLE
fixing the initial positions

### ISSUE THREAD

**Issue by tyluckyma** [ai-tor/DeepGTAV#4]
Hi @ai-tor 

I'm thinking of working on the initial position problem tomorrow, so just open this post for discussion. Have you fixed it? 

My idea is probably specify a rectangle region within the urban area (basically the range of x and y). Firstly randomly pick one point with z=0 and then use PATHFIND::GET_CLOSEST_ROAD() to get the road locations, and then place the player on it. 

I think it's important to put more attention on the urban roads instead of the country side, because the transportation there is more complicated and probably can help the agent learn better. During the data collection process, I notice that you are changing the weather on a time base. Have you tried teleporting the player occationally to avoid spending too much time on country side/highway?

In addition, I haven't used PATHFIND::GET_CLOSEST_ROAD(). May I have your opinion?

**Comment by ai-tor** [comment]
Not completely, I reduced the "random" area in scenario.cpp so now appearing near the beach is less probable, but still some times the vehicle appears at weird places. BTW, the code that puts the vehicle in place is this (in scenario.cpp):

```
if (_initialPosX == -1) x = -3400 + static_cast <float> (rand()) / (static_cast <float> (RAND_MAX / (3600 + 3400)));
	else x = _initialPosX;

	if (_initialPosY == -1) y = -3600 + static_cast <float> (rand()) / (static_cast <float> (RAND_MAX / (7000 + 3600)));
	else y = _initialPosY;

	heading = static_cast <float> (rand()) / (static_cast <float> (RAND_MAX / 360));

	while (!PATHFIND::LOAD_ALL_PATH_NODES(TRUE)) WAIT(0);
	PATHFIND::GET_CLOSEST_MAJOR_VEHICLE_NODE(x, y, 0, &pos, 300, 300);
PATHFIND::LOAD_ALL_PATH_NODES(FALSE);
```
GET_CLOSEST_ROAD could work, but is not well documented. I did some tries long ago and as far as I remember, it returns and integer corresponding to a nodeID. Your idea is similar to what I am doing currently, but instead I am using GET_CLOSEST_MAJOR_NODE_ID.

Maybe it may be a good idea to do the following:
1. Generate random x and y in the rectangle region (covering most of the GTAV map)
2. Get the closest nodeID for the position
3. Check that the returned nodeID is valid with IS_VEHICLE_NODE_ID_VALID
4. Check that the coordinates are in a road with IS_POINT_ON_ROAD
5. Return to 1 while 3 and 4 are not met

What do you think?

Regarding your proposal of teleporting the player, I think it could be cause troubles during training if the agent uses an LSTM or some other type of recurrence, as it needs some kind of temporal and spatial correlation between frames.

Thanks! :)

**Comment by tyluckyma** [comment]
Hi @ai-tor 

I think I found some clues on this initial position problem. I simply used the followinng code:
```
// First: randomly generate initial position within pre-specifid region
xInitial = mapInitialRegion[0] + static_cast <float> (rand()) / (static_cast <float> (RAND_MAX / (mapInitialRegion[1] - mapInitialRegion[0])));
yInitial = mapInitialRegion[2] + static_cast <float> (rand()) / (static_cast <float> (RAND_MAX / (mapInitialRegion[3] - mapInitialRegion[2])));

// Second: find the nearest node with proper road type and heading
PATHFIND::GET_CLOSEST_VEHICLE_NODE_WITH_HEADING(xInitial, yInitial, 0, &nodeClosest2InitialPos, &roadHeading, nodeTypeAsphaltRoad, 3, 0);

// Third: place the car on that position
ENTITY::SET_ENTITY_HEADING(testVehicle, roadHeading);
ENTITY::SET_ENTITY_COORDS(testVehicle, nodeClosest2InitialPos.x, nodeClosest2InitialPos.y, nodeClosest2InitialPos.z, 1, 0, 0, 1);
VEHICLE::SET_VEHICLE_ON_GROUND_PROPERLY(testVehicle);
```
Here for mapInitialRange I used [-600,300,-2000,-600] (xMin,xMax,yMin,yMax) to roughly make it start in the downtown area. You may change to other range such as rough urban area [-1500, 1000, -3000, 0], or a rough whole land map area [-2000, 2000, -3000, 6000].

nodeTypeAsphaltRoad = 0. This refers to the node type, while 0 represents asphalt road, and 1 represent asphalt road/simple roads, 3 means water. When you start, let AI drive for 3-5 seconds first, because sometime the car will be teleported on the reverse driving road. 

According to my test, to start in downtown/urban area is relatively safer because some time I was teleported to a Military base and got shot and killed by the soldiers. (^_^)

**Comment by ai-tor** [comment]
Great! @tyluckyma !

I will implement your approach, it looks really nice! I have had some troubles with military and police also. Once I was collecting a dataset for more than 8 hours and eventually the police chased and killed me. But this is solved now, setting the police alert level at 0 every 10 seconds or so :).

Probably tomorrow will do an update with both your contributions!

**Comment by tyluckyma** [comment]
I see. I probably found a small bug here in the police alert:
```
float delay = ((float)(now - lastSafetyCheck)) / CLOCKS_PER_SEC;
	if (delay > 10) {
		//Avoid bad things such as getting killed by the police, robbed, dying in car accidents or other horrible stuff
		PLAYER::SET_EVERYONE_IGNORE_PLAYER(player, TRUE);
		PLAYER::SET_POLICE_IGNORE_PLAYER(player, TRUE);
		PLAYER::CLEAR_PLAYER_WANTED_LEVEL(player); // Never wanted

		// Put on seat belt
		PED::SET_PED_CONFIG_FLAG(ped, 32, FALSE);

		// Invincible vehicle
		VEHICLE::SET_VEHICLE_TYRES_CAN_BURST(vehicle, FALSE);
		VEHICLE::SET_VEHICLE_WHEELS_CAN_BREAK(vehicle, FALSE);
		VEHICLE::SET_VEHICLE_HAS_STRONG_AXLES(vehicle, TRUE);

		VEHICLE::SET_VEHICLE_CAN_BE_VISIBLY_DAMAGED(vehicle, FALSE);
		ENTITY::SET_ENTITY_INVINCIBLE(vehicle, TRUE);  
		ENTITY::SET_ENTITY_PROOFS(vehicle, 1, 1, 1, 1, 1, 1, 1, 1);

		// Player invincible
		PLAYER::SET_PLAYER_INVINCIBLE(player, TRUE);

		// Driving characteristics
		PED::SET_DRIVER_AGGRESSIVENESS(ped, 0.0);
		PED::SET_DRIVER_ABILITY(ped, 1.0);
	}
```
Seems like you didn't update lastSafetyCheck within the if. So will this update of the police alert executed every step after 10 secs?

**Comment by ai-tor** [comment]
You are absolutely right! Will commit this immediately!

Thank you very much!
