### ISSUE TITLE
GTAV exits unexpectedly

### ISSUE THREAD

**Issue by Gilbran9** [ai-tor/DeepGTAV#41]
Just installed the game and followed the instructions to add DeepGTAV. When I run the game, it exits unexpectedly after the loading screens with the characters. If I remove the DeepGTAV files, the game works well. Perhaps a game update broke DeepGTAV?

**Comment by Gilbran9** [comment]
Issue was solved by going back to a previous version of the .asi file.

**Comment by yanpanlau** [comment]
Hi Gilbran9, I am facing exactly same issue as yours. May I ask where I can find the previous version of the .asi file? Thanks

**Comment by Gilbran9** [comment]
Hello yanpanlau, you can just check the file history. Here is the one I am using:
https://github.com/ai-tor/DeepGTAV/blob/65d6b2f347ce9e919598fdfca1e828b12da3806c/bin/Release/DeepGTAV.asi

This is from the commit on March 2. If this doesn't work, try an earlier one. To do this, just go to the .asi file here on github:
https://github.com/ai-tor/DeepGTAV/blob/master/bin/Release/DeepGTAV.asi

 Then click on history. Then from the history, you can click on the "<>" on the file you want. This will take you to the page where you can download that specific .asi file. Let me know if this helps.

**Comment by cpgeier** [comment]
Seems like the last two commits don't work.


The latest version that works for me can be found here: https://github.com/ai-tor/DeepGTAV/blob/f208609bcf6e23c2fe9ada85f23c7ee27fd11661/bin/Release/DeepGTAV.asi

**Comment by ai-tor** [comment]
Thanks @cpgeier, I just pushed a cleaner working version
