### ISSUE TITLE
Is there any way to spawn the same exact world everytime?

### ISSUE THREAD

**Issue by gilbran9** [ai-tor/DeepGTAV#42]
I was hoping that the random seed parameters would do this but nothing happens. Is there any way to have the same exact world (vehicles/pedestrians), spawn? 

I'd like to make the same "drive" under different time conditions. The pedestrians and vehicles spawned change each time as even when the random seed value is set to a constant. 

Additionally, can we freeze time on the game?

**Comment by parsa-m** [comment]
@ai-tor it would be great if you could please provide an update about this ? Thanks  :)

**Comment by ai-tor** [comment]
Hi!

It is possible to spawn at the same place, same time and same weather everytime, but it is not possible to control "external" things such pedestrians and vehicles around, this "randomization" is internally managed by the game.

One possible idea would be to delete all objects around and manually place them every time.

I think freezing time is possible, probably by using the PAUSE_CLOCK native or by setting the same time on each iteration of the script with SET_CLOCK_TIME. Still, I am not sure if that would kill the randomness.
