### ISSUE TITLE
Steering not working. Maybe configure memory offsets or use CONTROL_NORMAL?

### ISSUE THREAD

**Issue by andrebower** [ai-tor/DeepGTAV#43]
The values for steering, throttle and break are zero for me. I have the game Version VER_1_0_877_1_STEAM  (You mentioned in #3 VER_1_0_877_1_NOSTEAM works for you)

If I need different memory offsets for the values I think it would be nice to be able to configure this instead of hard coded values. 

You think my STEAM version needs different offsets or the issue has another source.

**Comment by andrebower** [comment]
Okay i checked out the code and am now using GET_CONTROL_NORMAL to get the inputs for steering etc. This works perfectly however i discovered something very confusing.

When i set the throttle command to 0.2 nothing happens. The car starts speeding up with a throttle command of 0.25 or something. However this is mapped to 0.01 when gathering the throttle value with GET_CONTROL_NORMAL. The mapping is kinda awkward. 1.0 is mapped to 1.0.

**Comment by ai-tor** [comment]
Hey! I just checked and the memory offsets are working. Do you have your GTAV game updated to the last version?

Regarding the braking and throttle, are mapped as follows:

Throttle:
0.0 to 1.0 forward acceleration
0.0 to -1.0 backward acceleration

Brake:
0.0 to 1.0 braking, either when going from forward to backward or viceversa. So braking is only > 0 when the vehicle is stopping.

Regarding the mapping of GET_CONTROL_NORMAL to the memory offset, yeah, it looks like it is not linear.

Take into account, that if you get the values with GET_CONTROL_NORMAL, it will only work when you are driving the vehicle yourself, not using in-game's AI.

**Comment by piliwilliam0306** [comment]
Hi!
I set the throttle , brake, steering to True, but the values don't seem to change.
Any ideas why?

![2017-07-28 12 44 46](https://user-images.githubusercontent.com/6561082/28702878-a4ca20d6-7392-11e7-81af-04ddc81e721b.png)

**Comment by StefanGerlach** [comment]
Just wanted to mention that for Version 1.0.1103.2 NON-Steam the offsets are:

Throttle:  0x90C
Brake:      0x910
Steering:  0x904

**Comment by arrowway** [comment]
@piliwilliam0306 Have you solved the problem?
