### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by pqhuy98** [ai-tor/DeepGTAV#45]
Hi,
It seems strange to me that frames I received from GTA V are all black, despite of GTA V is in 800x600 window mode and maximized. Do anyone recently succeed in working with DeepGTA V ? I suspect that the recent update from Rockstar stops me from receiving frames. I hope that it's solely my fault, since this framework is too great !

**Comment by cpgeier** [comment]
I was able to solve my issue by changing `	hWnd = ::FindWindow(NULL, "Grand Theft Auto V");` on line 14 of ScreenCapturer.cpp to `	hWnd = ::FindWindow(NULL, "Compatitibility Theft Auto V");`. Of course you can change it to anything you want, but the point is that I guess the win32 window screen capture doesn't work for some systems running GTAV, so renaming the window to a window that doesn't exist fixes the issue by capturing the entire screen. Once I recompiled the project in Visual Studio, I was able to view screenshots from the game with the code found in dataset.py.

Just remember the game must be full screen (Alt-Enter) after you make this change to capture the game.

The DeepGTAV.asi file I made can be found here:
https://drive.google.com/open?id=0B7gX17GpTrgxai0xai1jVGE1OGs

**Comment by pqhuy98** [comment]
Nice, it works ! Thank you so much.
