### ISSUE TITLE
Collecting speed information

### ISSUE THREAD

**Issue by michetonu** [ai-tor/DeepGTAV#49]
Hi,

Is it possible to collect the exact (relative or absolute) value for the speed of the car at a given moment? On the readme it seems that speed can only be "null" or "true".

Thanks!

**Comment by ai-tor** [comment]
Hi!

The message described in the Readme (Start or Config) is to tell DeepGTAV what values should return. If you send the Start message with speed set to "true" you will receive in return messages with the speed field filled with the car's absolute speed.

**Comment by michetonu** [comment]
Perfect, thanks so much!
