### ISSUE TITLE
Ways to obtain paths.xml

### ISSUE THREAD

**Issue by twmht** [ai-tor/DeepGTAV#5]
HI @ai-tor,

I can not find `paths.xml` in the GTAV directory, how to obtain that? 

What is the usage of `paths.xml`?

**Comment by ai-tor** [comment]
Hi @twmht ,

_paths.xml_ is a file used internally by GTAV that contains information about all the roads in the game, including lanes, maximum speed, widths, density...

By default it is encoded in the game binaries, so it can't be accessed directly. What I did was to extract it using [OpenIV](http://openiv.com/) and then reading it from the ScriptHook script. I use it to retrieve information about the lanes and create a reward function for lateral offset from their center, useful for Reinforcement Learning. If you use DeepGTAV for Supervised Learning (dataset generation) you don't need this file.

GitHub has a limit of 100 MB for files you can upload and _paths.xml_ is larger than that, so I can't put it into the repository. This afternoon I will upload it and provide a link to it in the Readme file, is it ok for you if I put it in Google Drive? I know in China you may have some issues to access Google services.

Sorry for the inconveniences!

**Comment by twmht** [comment]
@ai-tor 

Thanks for your quick response.

Can you talk more about using openiv to obtain `paths.xml`?

When I execute openiv and select the folder of GTAV, I have no idea what the next step is.

**Comment by ai-tor** [comment]
Hi!

It should be easy, it is just opening GTAV with OpenIV and looking around the directories, at some place you should find _paths.xml_, you don't need to execute any especial command, it will just appear magically.

I am not in front of my computer right now, so I can't know where exactly it is.

**Comment by twmht** [comment]
@ai-tor 

I look into `update/update.rpf` but can't find `paths.xml`

I am looking forward for your response.

Thanks.

**Comment by twmht** [comment]
By the way, for the code readability, Can you add more comment in the code?

**Comment by ai-tor** [comment]
Sure! I've actually never thought of releasing this work when I started so it is not super friendly. I will try to put comments in some parts of the code. Nevertheless, please email me if you need some clarifications :)

Thanks!

**Comment by Raj800** [comment]
Hey, @ai-tor 
I have paths.ipl inside common.rpf
And the Drive link in Readme file for paths.xml isn't working right now.
What should I do now?
[paths.zip](https://github.com/ai-tor/DeepGTAV/files/1354619/paths.zip)
