### ISSUE TITLE
ScriptHookV fails for GTA V version 1.0.1103.2

### ISSUE THREAD

**Issue by rszeto** [ai-tor/DeepGTAV#50]
This library is not compatible with GTA V version 1.0.1103.2 (the "Gunrunning" update). This is likely because ScriptHookV has not been updated to support that GTA V version.

**Comment by ai-tor** [comment]
Yes, that is the case. We need to wait until Alexander Blade releases the new ScriptHookV version. Stay tuned to http://www.dev-c.com/gtav/scripthookv/

**Comment by cpgeier** [comment]
While we are waiting for the new ScriptHookV, I was able to downgrade to an earlier version of GTAV and use the older ScriptHookV with the resources below:
https://www.youtube.com/watch?v=7HWOGLtV7Ig
https://forum.fiverp.net/threads/downgrade-for-gta-v-v1032-steam.11748/

It just involves replacing a few files and skipping the launcher.

Hopefully this helps! Really disappointed in Take Two for the crack down on mods...
