### ISSUE TITLE
Some files were denied access when compile

### ISSUE THREAD

**Issue by HeroLzj** [ai-tor/DeepGTAV#51]
## Hello!
Thank you so much for sharing this program. 
We've had some problems with compiling. And we hope to get your help.
We tried to compile the project DeepGTAV.vcxproj but there were some compilation errors.
Compiled information display that multiple files are denied access.
bin\Release\DeepGTAV.asi
bin\Release\DeepGTAV.iobj
bin\Release\DeepGTAV.ipdb
bin\Release\dinput8.dll
bin\Release\ScriptHookV.dll 
They were denied access.
Do we need any other libraries? 
We want to know what your system environment and libraries are when you compile !
Thank you very much!

![oku](https://user-images.githubusercontent.com/25497092/27278641-7faecd7a-5514-11e7-8d55-236fe82cc122.png)

**Comment by ai-tor** [comment]
Hi @HeroLzj,

Those are all binary files, it is most probably a file rights problem. dinput8.dll and ScriptHookV.dll are already provided by this repo, and the other files should be automatically generated under bin/Release when compiling. 

Make sure you have access to the bin/Release folder and that dinput8.dll and ScriptHookV.dll are both there.

**Comment by chizhang529** [comment]
Hi @HeroLzj ,

I encountered this problem as well and it was caused by trying to compile and build when the game is running. And I believe this problem will disappear if you quit the game before compiling.
