### ISSUE TITLE
why negative value in SpeedRewarder?

### ISSUE THREAD

**Issue by chizhang529** [ai-tor/DeepGTAV#58]
Hi @ai-tor !

I noticed the variable `reward` could be -1.0 in `SpeedRewarder.cpp` and the reward is defined as
```python
float reward = ENTITY::GET_ENTITY_SPEED(vehicle) / setSpeed;
```
and I suppose `setSpeed` represents the speed we hope the vehicle to run. Since `ENTITY::GET_ENTITY_SPEED(vehicle)` always returns a positive float even the vehicle collides with an entity, how could `reward` possibly be negative?

If my reasoning here is correct, then this line of code
```cpp
if (reward < -1.0f) reward = -1.0f;
```
does not make sense.

Would you please elaborate on the definition of speed reward?

**Comment by manuelschmidt** [comment]
I am not sure how driving backwards is handled. Logically that should give a negative speed. The line therefore makes sense to give the reward signal in such a case a lower bound.

From the definition of ENTITY::GET_ENTITY_SPEED I don't see a restriction that speed has to be positive.

**Comment by ai-tor** [comment]
Yes, that is exactly the case, speed is negative when the vehicle drives backwards, this behavior is penalized.
