### ISSUE TITLE
How to display 3d bbox?

### ISSUE THREAD

**Issue by Lollipopwz** [ai-tor/DeepGTAV#59]
Thanks for your great job!
 hello @ai-tor , i'm using DeepGTAV. I wonder how to display 3D bounding box like https://www.youtube.com/watch?v=StR9tuaIwYw&t=16s

**Comment by Lollipopwz** [comment]
define DEBUG in Scenario.h...

**Comment by isamabdullah88** [comment]
Hi @Lollipopwz , I wanted to know, should I build the code after defining DEBUG? If so, where can I find the .sln file to build? Or how can I build?
thanks

**Comment by gyubeomim** [comment]
@isamabdullah88 

in Scenario.h 
- add `#define DEBUG`
- move `void setVehiclesList()` function from `private` to `public`
	
then in script.cpp
- add this function like
```
		while (server.clientConnected) {
			server.checkRecvMessage();
			server.checkSendMessage();
			server.scenario.run();

			server.scenario.setVehiclesList();
                 }
```

- build it as .asi file, and move those files to GTAV home folder.
- rerun GTAV
- run `VPilot` script, and it'll be appeared
- same as Pedestrians, use `setPedsList()` instead
<br/><br/>
![6](https://user-images.githubusercontent.com/18214498/36338627-f8d3d5a4-13f7-11e8-83ee-00c9f2e4c22d.PNG)

**Comment by mjjdick** [comment]
Hi，I found the 3D boundingbox sometimes can not bounding the vehicle and sometimes it will not display. Are there someone meet the same problem with me?
