### ISSUE TITLE
GTAV crashes with the latest DeepGTAV.asi

### ISSUE THREAD

**Issue by piliwilliam0306** [ai-tor/DeepGTAV#65]
Hi @ai-tor, 
I noticed that you fixed the memory offsets in your last commit.
Somehow GTAV crashes with the latest DeepGTAV.asi file you commited.
I confirmed that by restoring DeepGTAV.asi file from your previous commit.
Can you check again?
Thanks!

**Comment by ai-tor** [comment]
Hi @piliwilliam0306 

It is working for me, so it may be related to a number of other things. Can you specify which Windows and GTAV version are you using?

Also make sure, your scripthookv DLL is the last version (should be the same there is in this repo).

You can also try to compile the .asi file yourself if the problem persists

**Comment by ai-tor** [comment]
Hey, 

Just realized that my version is also crashing, but only when trying to set the reward in the dataset message. Try not to set it and tell me if it works.

**Comment by piliwilliam0306** [comment]
Hi @ai-tor,

I have version 1.0.350.1 on my windows 10 machine.
It crashes while it's loading the game without running the VPilot.
The paths.xml and ScriptHookV.dll file were installed in the GTAV installation directory from your repo, any possibility that those files are outdated in the repo?
I will try to compile .asi file later.
Thanks for your quick response!

**Comment by ai-tor** [comment]
I am using GTAV version 1.0.350.2, so that is a clear difference, try to update the game

**Comment by piliwilliam0306** [comment]
Hi,
I compiled with VS 2013 then it worked!
Thanks for your help!

**Comment by xyyue** [comment]
Hi @ai-tor GTAV still crashes for me, I have done the following:
1. clone the latest version. 
2. add path.xml into the installation direction
3. tried recompile the project.

It is still not working for me. I'm wondering whether you have any idea on this?
Thank you so much!!
