### ISSUE TITLE
Exception when loading paths.xml

### ISSUE THREAD

**Issue by LemonAniLabs** [ai-tor/DeepGTAV#7]
Hi @ai-tor 

I try to load paths.xml, but there was an exception occurred.
I found the reason was nodes will out of range, that is very strange.
Because, you have written try catch in the code section.

```
try {
      node1 = nodes.at(node1.id);
      node2 = nodes.at(node2.id);
}catch (const std::out_of_range) {
//Empty on purpose
}
```
<img src="https://cloud.githubusercontent.com/assets/6212976/21170131/59c6bc9e-c1fd-11e6-9660-4e56dc6f1061.png" data-canonical-src="https://cloud.githubusercontent.com/assets/6212976/21170131/59c6bc9e-c1fd-11e6-9660-4e56dc6f1061.png" width="300" />
</br></br></br>
Any idea?
Thanks.

**Comment by ai-tor** [comment]
Hi!

I will check this in a few hours and return back to you. Please make sure _paths.xml_ is in your GTAV dir and also, could you tell me which reward function have you set in _config.ini_?

Thanks! :)

**Comment by LemonAniLabs** [comment]
Hi @ai-tor 

paths.xml at the same folder with GTAV.exe and I use 
{mode=1, reward=1} in config.ini

Thank you~~~

**Comment by ai-tor** [comment]
Hi @LemonAniLabs ,

Everything fine with your setup then. Will check once I get home. :)

**Comment by ai-tor** [comment]
Hi @LemonAniLabs ,

GTAV just got a new update and crashed ScriptHookV, so we need to wait until Alexander Blade releases an update for the new version. Probably two or three days.

I will get back to you once this is solved!

**Comment by ai-tor** [comment]
Yup... late, the game started the update and I wasn't in front of the computer. My mistake :)

**Comment by ai-tor** [comment]
Hi @LemonAniLabs !

Looked into the issue and for me it is working well. Your computer is haunted! Have you compiled the project yourself or are you using the provided binary?

**Comment by LemonAniLabs** [comment]
Hi @ai-tor 

I found the reason is ScriptHookVDotNet in GTAV dir, and scripthookvdotnet will let c++ exception escape DLL.

[Script Hook V .NET is interfering with exception catching in C++ ASI plugins #258](https://github.com/crosire/scripthookvdotnet/issues/258)

Anything will be fine if I remove scripthookvdotnet.asi and scripthookvdotnet..dll.

Thanks.

**Comment by ai-tor** [comment]
Wow! This is creepy! 

Thanks for sharing the cause, good to know! :)

**Comment by monajalal** [comment]
Does that mean that we can't have Script Hook V and Script Hook V.net at the same time in the GTAV directory? I used to have them at the same time and start the game with renderdoc and then it crashed. Someone from Princeton deep driving team used these two together to run his cs scripts for controlling the game scenes (or say creating a camera object).

**Comment by LemonAniLabs** [comment]
Hi @monajalal  
Script Hook V and Script Hook VDotNet can be used at the same time. But hookVDotNet will redirect exception, lead to try....catch block in script hook v not work.
Some exception(maybe critical exception) will let GTA crash, but some exception will just crash the hack-plugin.
