### ISSUE TITLE
ScreenCapture problem in windowed mode

### ISSUE THREAD

**Issue by alkorang** [ai-tor/DeepGTAV#73]
When I run GTA5 in windowed mode, layered windows are also captured with it.
Also, the boundary of the images start from top left of my monitor, not game screen itself.
This problem happens especially when I use smaller resolutions than desktop resolution.

**Comment by alkorang** [comment]
Oh, there is commented part of getting only GTA5 context in [ScreenCapturer.cpp](https://github.com/ai-tor/DeepGTAV/blob/9aae33c56b601f3a418904aaf255b56bfd8140f3/ScreenCapturer.cpp#L14-L15).
I chaged this:
```
	//hWnd = ::FindWindow(NULL, "Grand Theft Auto V");
	hWindowDC = GetDC(NULL);
```
to this.
```
	hWnd = ::FindWindow(NULL, "Grand Theft Auto V");
	hWindowDC = GetDC(hWnd);
```
And it captures only game frames perfectly!
Why did you delete this part? Is there any problem with it?

**Comment by ai-tor** [comment]
It seems that the previous solution was not working for all users. Depending on Windows version they got just black pixels.

The current solution works for everybody, but if you prefer it this way go ahead :)
