### ISSUE TITLE
Link broken for paths.xml

### ISSUE THREAD

**Issue by half-potato** [ai-tor/DeepGTAV#75]
The link in the readme to paths.xml is broken. Where can I find this file?

**Comment by hmtai6** [comment]
same here.

**Comment by half-potato** [comment]
Turns out you don't need it.

**Comment by LemonAniLabs** [comment]
@half-potato @hmtai6 @andyhahaha 
I have downloaded paths.xml before.
https://drive.google.com/file/d/0B6pR5O2YrmHnNU9EMDBSSFpMV00/view?usp=sharing

**Comment by andyhahaha** [comment]
@LemonAniLabs  Thanks very much!!!
