### ISSUE TITLE
Trouble in receiving throttle, brake and steering

### ISSUE THREAD

**Issue by Sophistt** [ai-tor/DeepGTAV#77]
Hi, I use VPilot to receive the messages to from DeepGTAV as you said, but it seems some problems happen when I receive the message. I can get the correct data such as 'frame', 'speed', 'reward' and so on, but the data of 'throttle', 'brake' and 'steering'  do not reflect correctly, which is always keeping as 0 or 1. Does the game version or driving mode influence this?

**Comment by qmind** [comment]
@Sophistt yes, I have updated gtav to the newest version and solved this problem.
