### ISSUE TITLE
CORE: An exception occurred while executing 'DeepGTAV.asi' (0x00007FFB6B30F8D0), id 31 # with the lastest version

### ISSUE THREAD

**Issue by TommyAnqi** [ai-tor/DeepGTAV#78]
The DeepGTAV is really an amazing project to help us collect the data from the game. 

However, I have met a problem which made the game crashing. I have tried to use different GTAV versions (the lastest and an old version) and run the code but the same error happened.  

If you have any idea what happens, I really appreciate it.

**Comment by Cupido10** [comment]
I got the same problem too.

**Comment by andyhahaha** [comment]
I got the same issue. Any suggestion?

**Comment by Cupido10** [comment]
I found the solution that use the old version code and it can work properly. Here is the old version: https://github.com/ai-tor/DeepGTAV/tree/65d6b2f347ce9e919598fdfca1e828b12da3806c

**Comment by andyhahaha** [comment]
It works. Thanks a lot!!!
