### ISSUE TITLE
Traffic signs

### ISSUE THREAD

**Issue by TairuiWang** [ai-tor/DeepGTAV#83]
Currently, I am trying to add the 'trafficSigns' part in your code. It seems there are no similar functions like '**GET_PED_TYPE**' or '**IS_THIS_MODEL_A_CAR**' for traffic signs. According to [this](http://orfe.princeton.edu/~alaink/SmartDrivingCars/Visitors/FilipowiczVideoGamesforAutonomousDriving.pdf), we need to find out the traffic sign model by ourselves. I checked [this](http://gtaforums.com/topic/788275-models-color-hashes/). I am not sure whether is it useful because the 'Hash' type in your code is 'long unsigned', but some of the hashes in this link is negative. 

I am really appreciate if you can give me some advice.

**Comment by caunion** [comment]
it seems in your 2nd link, the hash_id is a `int32`. I guess it's OK if you convert them to `unsigned long` in code.

More over, I found this [link](http://objects.codeshock.hu/gallery.php?search=stop&page=1&perpage=12) to be a great place for you to looking for objects and ids. A quick search for keyword 'sign' in the website above, you can see most of traffic signs and their object id.
