### ISSUE TITLE
Is it possible to build a virtual LiDAR scanner attached to a vehicle?

### ISSUE THREAD

**Issue by gdpinchina** [ai-tor/DeepGTAV#84]
A 3D LiDAR can collect 3D point clouds of the environment. That should be very helpful in an auto driving simulation training.  If this is possible, which APIs should I pay attention to? Or, any mods have made this come true?

**Comment by dtmoodie** [comment]
I believe this is possible. When I was poking around I found that you could do Ray tracing. With that you simulate lidar.

**Comment by gdpinchina** [comment]
Thank you! This help me a lot! I'm working on it.

**Comment by Cuky88** [comment]
@gdpinchina Any progress here? I will try to develop such a mod, too. Maybe we can work together?

**Comment by gdpinchina** [comment]
I've already developed a prototype virtual LiDAR device. I didn't test it much and it may have some bugs. Now I am putting it to my repo

**Comment by gdpinchina** [comment]
@Cuky88

**Comment by dominikandreas** [comment]
@gdpinchina can you tell us a bit about the performance / framerate impact?

**Comment by gyubeomim** [comment]
Thank you so much @gdpinchina 
I was looking forward to using virtual LIDAR sensor in GTAV and you made it open source.

I'll try your code and maybe I'll get you some feedback, Thx! :-)

**Comment by Cuky88** [comment]
@gdpinchina I didn't try it, yet, but it looks good. I'll convert it to C# and then test it. Thank you for publishing the mod.

**Comment by gdpinchina** [comment]
I have updated readme in my lidar repo for DeepGTAV. Sample rate is determined by the calling frequency of  API `GetPointClouds`.  For cheaper computation burden, I assume the vehicle is static in each horizontal sample instead of updating the position of lidar in each point sample.  Also the same solution is applied to coordination transformation. @dominikandreas
