### ISSUE TITLE
it doesn't play the game automatically

### ISSUE THREAD

**Issue by monajalal** [ai-tor/DeepGTAV#9]
Hi Aitor,
Seems it doesn't play the game automatically. I copied the stuff from the bin folder and pasted them in the GTA5 directory as you see here:
![deepgtav5](https://cloud.githubusercontent.com/assets/1892917/22043666/46198232-dcd6-11e6-9cf6-831e7fde433e.PNG)
but this is what I see (I can see the weather changes):
![jan-17-2017-clip-0001](https://cloud.githubusercontent.com/assets/1892917/22043676/587bd5ba-dcd6-11e6-9600-99e6ed844e8f.jpg)

Any idea what could have wrong with my setup?

**Comment by monajalal** [comment]
So I had forgotten to use your saved games and after I did, it started from a car in a road similar to what you see below, however still I have to steer the car and it is not steered automatically:
![jan-17-2017-clip-0002](https://cloud.githubusercontent.com/assets/1892917/22050648/50eee810-dd02-11e6-8fd3-790e4c00657c.jpg)
Can you please hint why Reinforcement Learning or in general automatic driving is not working?

**Comment by twmht** [comment]
@monajalal 

This repository does not contain the reinforcement learning or supervised learning to inference the actions.

Instead, you need to look at this https://github.com/ai-tor/VPilot, which plays a server role to send the command to the GTA.

However, there is no training model available, you need to use DeepGTAV to generate the dataset and train the dataset by VPilot.

**Comment by monajalal** [comment]
@twmht so I looked at VPilot and found no tutorial how to set it up or how to use those Python file. Can you please have a look at this link? https://github.com/ai-tor/VPilot/issues/4
Thanks a lot! 
Also I assume you run VPilot on a Linux machine while GTA5 is run on Windows, right? Or should I run VPilot also on Windows?

**Comment by ai-tor** [comment]
Hi @monajalal and thanks @twmht for the answer :)

If you set mode=0 in your DeepGTAV config.ini file you should see the car moving by itself using ingame's AI (dataset generation mode).

In mode=1 you need VPilot or similar software to connect your self-driving agent to DeepGTAV and send the commands to it. I've never tested VPilot in Windows, but it should work also. Usually what I do is connecting VPilot to DeepGTAV remotely, where VPilot runs on a Linux machine with a powerful GPU.

I will continue the discussion of VPilot in its repository, to keep things separated.

**Comment by monajalal** [comment]
just confirming that mode=0 works for me and the car drives automatically using the game AI. I will close the issue once I am successfully done with the VPilot connection with DeepGTAV. Thank you so much.
