### ISSUE TITLE
GTA crashes with the plugin

### ISSUE THREAD

**Issue by Lakshmibharadwaj** [ai-tor/DeepGTAV#92]
Hi Aitor,

Thanks for the DGTAV plugin, its wonderful job that you have done creating such a cool plugin.

 I followed all the steps that you have mentioned, But when I start the GTAVlauncher in offline mode it crashes, I cant play the game or load the plugin.
I have the version 1290.1, I downgraded the version to 1103.2. Before following the steps I played the game and it worked without any issues.
 I copied the release folder to my GTA root directory and savegame folder into Documents/profiles. As u said I tried to launch the game, It crashes.

Can you please help me in resolving this issue. Thanks a ton in advance.

**Comment by nitr0x1de** [comment]
After quite a lot of head-scratching I've made it work in the following way for 1.0.1290.1 (Rockstar download, not Steam):

1. Copy  DeepGTAV/bin/release contents to GTAV root folder
2. Get latest release of Script Hook V from [here](http://www.dev-c.com/files/ScriptHookV_1.0.1290.1.zip) and overwrite in root folder 
3. Get Launcher Bypass from [here](https://www.gta5-mods.com/tools/gtavlauncherbypass/download/19399) and overwrite in root folder (not sure it's actually needed)
4. Copy contents of  DeepGTAV/bin/SaveGame to Documents\Rockstar Games\GTA V\Profiles\<name of profile>\
5. Install OpenIV from [here](http://openiv.com/)
6. Start OpenIV; Select GTA V location; I opened an *.rpf file and looked at a texture dictionary (don't think it's relevant, however Starting OpenIV is!); Close OpenIV
7. Start GTA with GTAV.exe
8. You can test with [VPilot](https://github.com/aitorzip/VPilot)(e.g. drive script) if you can get a connection to DeepGTAV after the game finished loading to story mode; drive should output "Successfully connected to DeepGTAV" if all goes well
9. Enjoy!
